/* ----------------------------- CSS ----------------------------- */
registerCourse({ id:"css", name:"CSS", tagline:"Od první barvy po seniorní layouty a moderní CSS", color:"var(--c-css)", engine:"css", status:"live", code:"a { color: …; }",
  tiers:[
    { id:"start", optional:true, name:"Úplné základy", desc:"Pro úplné nováčky: co je HTML a CSS, jak se čte pravidlo, k čemu jsou závorky a středníky. Asi 10 minut, nic nezamyká.", glyph:"0" },
    { id:"junior", name:"Junior", desc:"Selektory, box model, flexbox a grid. Základ, bez kterého to nejde.", glyph:"JR" },
    { id:"medior", name:"Medior", desc:"Specificita, pozicování, typografie, responzivita a design tokeny.", glyph:"MD" },
    { id:"senior", name:"Senior", desc:"Animace s ohledem na přístupnost, moderní CSS a projekty z praxe.", glyph:"SR" },
    { id:"novinky", name:"Novinky 2025–26", after:"medior", desc:"Co se v CSS řeší právě teď: oklch, anchor positioning, scroll-driven animace, style queries, if(). U každé funkce vidíš, jak je na tom podpora.", glyph:"NEW" },
  ],
  modules:[
    { id:"start", tier:"start", name:"První krůčky", sub:"Pět krátkých lekcí s vysvětlením krok za krokem", color:"var(--m-content)", glyph:"0" },
    { id:"sel",   tier:"junior", name:"Selektory a barvy",   sub:"Jak CSS najde prvek a co s ním udělá",        color:"var(--m-content)", glyph:".a" },
    { id:"box",   tier:"junior", name:"Box model",           sub:"Obsah, padding, rámeček, šířka",              color:"var(--m-padding)", glyph:"▭" },
    { id:"flex",  tier:"junior", name:"Flexbox",             sub:"Rozložení prvků v řadě i ve sloupci",         color:"var(--m-border)",  glyph:"⇆" },
    { id:"grid",  tier:"junior", name:"CSS Grid",            sub:"Dvourozměrné mřížky a layout stránky",        color:"var(--m-margin)",  glyph:"#" },
    { id:"zak-jr",tier:"junior", project:true, name:"Zakázka: první klient", sub:"Celá stránka podle zadání a stylu. Otevře se po modulech Box model a Flexbox.", color:"var(--accent)", glyph:"◧" },
    { id:"adv",   tier:"medior", name:"Pokročilé selektory", sub:"Pseudotřídy, atributy, pseudo-elementy, specificita", color:"var(--m-content)", glyph:":n" },
    { id:"pos",   tier:"medior", name:"Pozicování",          sub:"relative, absolute, sticky, z-index, inset",  color:"var(--m-padding)", glyph:"xy" },
    { id:"typo",  tier:"medior", name:"Jednotky a typografie", sub:"rem, ch, line-height, clamp()",             color:"var(--m-border)",  glyph:"Aa" },
    { id:"resp",  tier:"medior", name:"Responzivita",        sub:"Obrázky, zalamování, auto-fit, @media, @container", color:"var(--m-margin)", glyph:"▯▭" },
    { id:"vars",  tier:"medior", name:"Proměnné a motivy",   sub:"Custom properties, tmavý motiv, calc()",      color:"var(--m-content)", glyph:"--" },
    { id:"zak-md",tier:"medior", project:true, name:"Zakázky: medior", sub:"Landing page a dashboard v konkrétním vizuálním stylu.", color:"var(--accent)", glyph:"◧" },
    { id:"anim",  tier:"senior", name:"Přechody a animace",  sub:"transition, transform, @keyframes, reduced motion", color:"var(--m-padding)", glyph:"↻" },
    { id:"modern",tier:"senior", name:"Moderní CSS",         sub:":has(), aspect-ratio, logické vlastnosti, @layer, nesting", color:"var(--m-border)", glyph:"✦" },
    { id:"boss",  tier:"senior", name:"Komponenty z praxe",  sub:"Karta produktu, ceník, modální okno",          color:"var(--m-margin)",  glyph:"★" },
    { id:"zak-sr",tier:"senior", project:true, name:"Zakázka: senior", sub:"Výrazný styl, interakce a přístupnost dohromady.", color:"var(--accent)", glyph:"◧" },
    { id:"nov-color", tier:"novinky", name:"Barvy a text nové generace", sub:"oklch(), color-mix(), relativní barvy, light-dark(), text-wrap", color:"var(--m-content)", glyph:"ok" },
    { id:"nov-ui",    tier:"novinky", name:"Interakce bez JavaScriptu",  sub:"anchor positioning, @starting-style, height: auto, field-sizing", color:"var(--m-padding)", glyph:"⚓" },
    { id:"nov-scroll",tier:"novinky", name:"Scroll a pohyb",             sub:"scroll-snap, scroll-driven animace, view()", color:"var(--m-border)", glyph:"⇣" },
    { id:"nov-logic", tier:"novinky", name:"Logika v CSS",               sub:"style queries, @scope, if(), sibling-index()", color:"var(--m-margin)", glyph:"if" },
    { id:"zak-new",   tier:"novinky", project:true, name:"Zakázka: moderní stack", sub:"Mobilní prototyp postavený na nejnovějším CSS.", color:"var(--accent)", glyph:"◧" },
  ],
  levels:[],
  achievements:[
    {id:"mod-sel", name:"Selektorník",  desc:"Dokonči modul Selektory a barvy.", glyph:".a", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"css","sel")},
    {id:"mod-box", name:"Krabičkář",    desc:"Dokonči modul Box model.",         glyph:"▭",  color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"css","box")},
    {id:"mod-flex",name:"Flexpert",     desc:"Dokonči modul Flexbox.",           glyph:"⇆",  color:"var(--m-border)",  test:(s,cs)=>moduleDone(cs,"css","flex")},
    {id:"mod-grid",name:"Mřížkař",      desc:"Dokonči modul CSS Grid.",          glyph:"#",  color:"var(--m-margin)",  test:(s,cs)=>moduleDone(cs,"css","grid")},
    {id:"center",  name:"Mistr středu", desc:"Vycentruj prvek na obou osách.",   glyph:"◎",  color:"var(--m-margin)",  test:(s,cs)=>!!cs.done["flex-4"]},
    {id:"mod-adv", name:"Lovec selektorů", desc:"Dokonči modul Pokročilé selektory.", glyph:":n", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"css","adv")},
    {id:"mod-pos", name:"Navigátor",    desc:"Dokonči modul Pozicování.",        glyph:"xy", color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"css","pos")},
    {id:"mod-resp",name:"Gumový layout",desc:"Dokonči modul Responzivita.",      glyph:"▯▭", color:"var(--m-margin)",  test:(s,cs)=>moduleDone(cs,"css","resp")},
    {id:"mod-vars",name:"Tokenář",      desc:"Dokonči modul Proměnné a motivy.", glyph:"--", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"css","vars")},
    {id:"mod-anim",name:"Animátor",     desc:"Dokonči modul Přechody a animace.",glyph:"↻",  color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"css","anim")},
    {id:"mod-modern",name:"Na hraně specifikace",desc:"Dokonči modul Moderní CSS.",glyph:"✦",color:"var(--m-border)", test:(s,cs)=>moduleDone(cs,"css","modern")},
    {id:"debugger",name:"Debugger",     desc:"Oprav všechny úrovně typu „Oprav chybu“.", glyph:"bug", color:"var(--m-margin)", test:(s,cs)=>course("css").levels.filter(l=>l.kind==="debug").every(l=>cs.done[l.id])},
    {id:"boss-clean",name:"Bez záchranné sítě",desc:"Dokonči projekt bez nápovědy.", glyph:"★!", color:"var(--m-margin)", test:(s,cs)=>course("css").levels.some(l=>l.boss&&cs.done[l.id]?.clean)},
    {id:"basics",  name:"První krůček",  desc:"Projdi Úplné základy.", glyph:"0", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"css","start")},
    {id:"proj-1",  name:"První klient",  desc:"Dokonči první zakázku.", glyph:"◧", color:"var(--accent)", test:(s,cs)=>course("css").levels.some(l=>l.project&&cs.done[l.id])},
    {id:"proj-all",name:"Portfolio",     desc:"Dokonči všech 5 zakázek.", glyph:"◧◧", color:"var(--accent)", test:(s,cs)=>course("css").levels.filter(l=>l.project).every(l=>cs.done[l.id])},
    {id:"new-color",name:"Barvoznalec",  desc:"Dokonči modul Barvy a text nové generace.", glyph:"ok", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"css","nov-color")},
    {id:"new-ui",  name:"Bez skriptu",   desc:"Dokonči modul Interakce bez JavaScriptu.", glyph:"⚓", color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"css","nov-ui")},
    {id:"new-scroll",name:"Scroll master",desc:"Dokonči modul Scroll a pohyb.", glyph:"⇣", color:"var(--m-border)", test:(s,cs)=>moduleDone(cs,"css","nov-scroll")},
    {id:"new-logic",name:"CSS je programovací jazyk",desc:"Dokonči modul Logika v CSS.", glyph:"if", color:"var(--m-margin)", test:(s,cs)=>moduleDone(cs,"css","nov-logic")},
    {id:"perfect", name:"Tři hvězdy všude", desc:"Všechny úrovně CSS na 3 hvězdy.", glyph:"★★★", color:"var(--m-content)", test:(s,cs)=>course("css").levels.every(l=>cs.done[l.id]?.stars===3)},
  ]
});

