/* ----------------------------- HTML ----------------------------- */
const HTML_BASE=`.scene{font:16px/1.5 system-ui,sans-serif;color:#14203a}h1,h2,h3{line-height:1.2;margin:.4em 0}a{color:#2f5bd3}img{max-width:100%;min-height:40px;min-width:80px;background:#e2e8f0;border-radius:6px;display:inline-block}`;
const SEM_CSS=`.header,header{display:flex;justify-content:space-between;align-items:center;background:#14203a;color:#fff;padding:10px 14px;border-radius:10px}.header a,header a{color:#fff;margin-left:12px}.main,main{padding:6px 2px}.footer,footer{border-top:1px solid #cbd5e1;padding-top:8px;font-size:13px;color:#475569}`;
const TABLE_CSS=`table{border-collapse:collapse;min-width:260px}caption{font-weight:800;text-align:left;margin-bottom:6px}th,td{border:1px solid #cbd5e1;padding:6px 10px;text-align:left}thead th{background:#14203a;color:#fff}tbody tr:nth-child(even){background:#f1f5f9}`;
const FORM_CSS=`form{display:grid;gap:8px;max-width:340px}label{font-weight:700;font-size:14px}input,select,textarea{font:inherit;padding:8px 10px;border:1px solid #94a3b8;border-radius:8px;background:#fff}textarea{min-height:70px}button{font:inherit;font-weight:700;padding:9px 14px;border:0;border-radius:8px;background:#2f5bd3;color:#fff;cursor:pointer;justify-self:start}input:focus-visible,select:focus-visible,textarea:focus-visible,button:focus-visible{outline:3px solid #f2c96b;outline-offset:1px}`;

registerCourse({ id:"html", name:"HTML", tagline:"Struktura, sémantika, formuláře a přístupnost", color:"var(--c-html)", engine:"html", status:"live", code:"<h1>…</h1>",
  tiers:[
    { id:"junior", name:"Junior", desc:"Prvky, atributy, nadpisy, sémantická kostra stránky a tabulky.", glyph:"JR" },
    { id:"medior", name:"Medior", desc:"Formuláře, které se dobře vyplňují, a přístupnost pro klávesnici i čtečky.", glyph:"MD" },
    { id:"senior", name:"Senior", desc:"Moderní nativní prvky (details, dialog, popover, picture) a velký refaktor.", glyph:"SR" },
  ],
  modules:[
    { id:"base",  tier:"junior", name:"Základy HTML", sub:"Prvky, atributy, obrázky, nadpisy", color:"var(--c-html)", glyph:"<>" },
    { id:"sem",   tier:"junior", name:"Sémantika", sub:"header, nav, main, article, figure, aside", color:"var(--m-content)", glyph:"§" },
    { id:"tab",   tier:"junior", name:"Tabulky", sub:"caption, thead, th a scope", color:"var(--m-padding)", glyph:"▦" },
    { id:"form",  tier:"medior", name:"Formuláře", sub:"label, typy polí, required, fieldset, select", color:"var(--m-border)", glyph:"[_]" },
    { id:"a11y",  tier:"medior", name:"Přístupnost", sub:"Tlačítka, aria-label, text odkazů, lang, alt", color:"var(--m-margin)", glyph:"♿" },
    { id:"modern",tier:"senior", name:"Moderní HTML", sub:"details, dialog, popover, picture", color:"var(--m-content)", glyph:"✦" },
    { id:"hboss", tier:"senior", name:"Projekt z praxe", sub:"Přepiš div polévku na sémantickou stránku", color:"var(--accent)", glyph:"★" },
  ],
  levels:[
  { id:"h-1", module:"base", xp:100, title:"Nadpis a odstavec",
    theory:`<p>HTML popisuje, <b>co</b> je na stránce. Prvek má otevírací a zavírací značku: <code>&lt;p&gt;Text&lt;/p&gt;</code>.</p><p><code>&lt;h1&gt;</code> je hlavní nadpis stránky, <code>&lt;p&gt;</code> odstavec.</p>`,
    task:`Vytvoř nadpis <code>h1</code> s textem <b>Vítej v Kaskádě</b> a pod ním libovolný odstavec.`,
    fixed:HTML_BASE, starter:`<!-- napiš sem svůj HTML -->\n`,
    solution:`<h1>Vítej v Kaskádě</h1>\n<p>Tady se učím psát HTML.</p>`,
    hints:["Nadpis: <code>&lt;h1&gt;…&lt;/h1&gt;</code>.","Odstavec: <code>&lt;p&gt;…&lt;/p&gt;</code> hned pod nadpisem."],
    checks:[
      {label:"Na stránce je h1 s textem Vítej v Kaskádě", test:c=>c.text("h1")==="Vítej v Kaskádě"},
      {label:"Pod nadpisem je neprázdný odstavec", test:c=>{const p=c.q("h1 ~ p");return !!p&&p.textContent.trim().length>0}} ] },
  { id:"h-2", module:"base", xp:120, title:"Odkaz ven",
    theory:`<p>Atributy doplňují prvkům informace. Odkaz potřebuje atribut <code>href</code> s adresou: <code>&lt;a href="https://…"&gt;text&lt;/a&gt;</code>.</p><p><code>target="_blank"</code> otevře odkaz v novém panelu.</p>`,
    task:`Vytvoř odkaz s textem <b>Dokumentace</b> na <code>https://developer.mozilla.org</code>, který se otevře v novém panelu.`,
    fixed:HTML_BASE,
    starter:`<p>Víc informací najdeš v </p>`,
    solution:`<p>Víc informací najdeš v <a href="https://developer.mozilla.org" target="_blank">Dokumentace</a></p>`,
    hints:["Odkaz je prvek <code>&lt;a&gt;</code> s atributem <code>href</code>.","Nový panel: přidej <code>target=\"_blank\"</code>."],
    checks:[
      {label:"Odkaz vede na https://developer.mozilla.org", test:c=>/^https:\/\/developer\.mozilla\.org\/?$/.test(c.q("a")?.getAttribute("href")||"")},
      {label:"Text odkazu je Dokumentace", test:c=>c.text("a")==="Dokumentace"},
      {label:"Otevře se v novém panelu", test:c=>c.q("a")?.getAttribute("target")==="_blank"} ] },
  { id:"h-3", module:"base", xp:140, title:"Nákupní seznam",
    theory:`<p>Odrážkový seznam je <code>&lt;ul&gt;</code>, každá položka <code>&lt;li&gt;</code>. Číslovaný seznam je <code>&lt;ol&gt;</code>.</p><p>Prvky se do sebe vnořují — <code>li</code> patří dovnitř <code>ul</code>.</p>`,
    task:`Vytvoř odrážkový seznam se třemi položkami: <b>mléko</b>, <b>chléb</b>, <b>káva</b>.`,
    fixed:HTML_BASE,
    starter:`<h2>Nakoupit</h2>\n`, solution:`<h2>Nakoupit</h2>\n<ul>\n  <li>mléko</li>\n  <li>chléb</li>\n  <li>káva</li>\n</ul>`,
    hints:["Obal položky do <code>&lt;ul&gt;…&lt;/ul&gt;</code>.","Každá položka je <code>&lt;li&gt;mléko&lt;/li&gt;</code>."],
    checks:[
      {label:"Je tu odrážkový seznam ul", test:c=>!!c.q("ul")},
      {label:"Má přesně 3 položky", test:c=>c.qa("ul > li").length===3},
      {label:"Položky: mléko, chléb, káva", test:c=>c.qa("ul > li").map(e=>e.textContent.trim().toLowerCase()).join(",")==="mléko,chléb,káva"} ] },

  { id:"h-4", module:"base", xp:120, title:"Obrázek a alt",
    theory:`<p>Obrázek je párová výjimka — nemá zavírací značku: <code>&lt;img src="soubor.jpg" alt="Popis"&gt;</code>.</p><p><code>alt</code> je text pro lidi, kteří obrázek nevidí (čtečka obrazovky, pomalé připojení). Popiš, <b>co je na obrázku</b>, ne „obrázek“ nebo název souboru.</p>`,
    task:`Pod odstavec vlož obrázek <code>kavarna.jpg</code> s výstižným alternativním textem, třeba co je na fotce vidět.`,
    fixed:HTML_BASE, starter:`<p>Takhle to u nás vypadá:</p>\n`, solution:`<p>Takhle to u nás vypadá:</p>\n<img src="kavarna.jpg" alt="Útulná kavárna s dřevěnými stoly a baristou u kávovaru">`,
    hints:["Značka je <code>&lt;img&gt;</code> s atributy <code>src</code> a <code>alt</code>.","<code>&lt;img src=\"kavarna.jpg\" alt=\"Útulná kavárna s dřevěnými stoly\"&gt;</code>"],
    checks:[
      {label:"Je tu obrázek se src kavarna.jpg", test:c=>c.q("img")?.getAttribute("src")==="kavarna.jpg"},
      {label:"Má alt, který popisuje obsah (aspoň 3 slova)", test:c=>{const a=(c.q("img")?.getAttribute("alt")||"").trim();return a.split(/\s+/).length>=3&&!/obr[aá]zek|foto|kavarna\.jpg|image/i.test(a)}} ] },
  { id:"h-5", module:"base", xp:140, title:"Hierarchie nadpisů",
    theory:`<p>Nadpisy <code>h1</code>–<code>h6</code> tvoří osnovu stránky, jako obsah v knize. Na stránce je jeden <code>h1</code>, kapitoly jsou <code>h2</code>, podkapitoly <code>h3</code>. Úrovně nepřeskakuj — po <code>h2</code> nepatří rovnou <code>h4</code>.</p><p>Velikost nadpisu se řeší v CSS, ne výběrem úrovně.</p>`,
    task:`Udělej z textů osnovu: <b>Kavárna Zrnko</b> = h1, <b>Menu</b> a <b>Kontakt</b> = h2, <b>Káva</b> a <b>Čaj</b> (patří pod Menu) = h3.`,
    fixed:HTML_BASE, starter:`<div>Kavárna Zrnko</div>\n<div>Menu</div>\n<div>Káva</div>\n<p>Espresso, flat white, filtr.</p>\n<div>Čaj</div>\n<p>Sencha, earl grey, rooibos.</p>\n<div>Kontakt</div>\n<p>Veveří 42, Brno</p>`,
    solution:`<h1>Kavárna Zrnko</h1>\n<h2>Menu</h2>\n<h3>Káva</h3>\n<p>Espresso, flat white, filtr.</p>\n<h3>Čaj</h3>\n<p>Sencha, earl grey, rooibos.</p>\n<h2>Kontakt</h2>\n<p>Veveří 42, Brno</p>`,
    hints:["Přepiš <code>&lt;div&gt;</code> na správné nadpisy — otevírací i zavírací značku.","<code>&lt;h1&gt;Kavárna Zrnko&lt;/h1&gt;</code>, pak <code>&lt;h2&gt;Menu&lt;/h2&gt;</code>, <code>&lt;h3&gt;Káva&lt;/h3&gt;</code>…"],
    checks:[
      {label:"Jeden h1: Kavárna Zrnko", test:c=>c.qa("h1").length===1&&c.text("h1")==="Kavárna Zrnko"},
      {label:"h2: Menu a Kontakt", test:c=>c.qa("h2").map(e=>e.textContent.trim()).join("|")==="Menu|Kontakt"},
      {label:"h3: Káva a Čaj", test:c=>c.qa("h3").map(e=>e.textContent.trim()).join("|")==="Káva|Čaj"},
      {label:"Úrovně se nepřeskakují", test:c=>{let last=0;for(const h of c.qa("h1,h2,h3,h4,h5,h6")){const n=+h.localName[1];if(n>last+1)return false;last=n}return true}} ] },
  { id:"h-6", module:"base", xp:120, title:"Důraz v textu",
    theory:`<p><code>&lt;strong&gt;</code> = důležité (čtečka to může zdůraznit), <code>&lt;em&gt;</code> = důraz, jak bys ho řekl(a) nahlas. Prohlížeč je zobrazí tučně a kurzívou, ale jde o <b>význam</b>, ne o vzhled. Pro čistě vizuální tučné písmo použij CSS.</p>`,
    task:`Ve větě označ slovo <b>zdarma</b> jako důležité a slovo <b>opravdu</b> jako důraz.`,
    fixed:HTML_BASE, starter:`<p>Doprava je zdarma a stojí to opravdu za to.</p>`, solution:`<p>Doprava je <strong>zdarma</strong> a stojí to <em>opravdu</em> za to.</p>`,
    hints:["Důležité = <code>&lt;strong&gt;</code>, důraz = <code>&lt;em&gt;</code>.","<code>&lt;strong&gt;zdarma&lt;/strong&gt;</code> a <code>&lt;em&gt;opravdu&lt;/em&gt;</code>"],
    checks:[
      {label:"zdarma je ve strong", test:c=>c.text("strong")==="zdarma"},
      {label:"opravdu je v em", test:c=>c.text("em")==="opravdu"},
      {label:"Věta zůstala celá", test:c=>c.text("p").replace(/\s+/g," ")==="Doprava je zdarma a stojí to opravdu za to."} ] },

  { id:"hs-1", module:"sem", xp:180, title:"Kostra stránky",
    slides:[{ title:"Sémantické prvky = mapa stránky", html:`<p>Stránka postavená jen z <code>&lt;div&gt;</code> vypadá dobře, ale prohlížeč, vyhledávač ani čtečka nevědí, co je co. Sémantické prvky to říkají:</p>
      <div class="sem-map"><div class="sm h">&lt;header&gt; záhlaví<div class="sm n">&lt;nav&gt; navigace</div></div><div class="sm m">&lt;main&gt; hlavní obsah — jen jeden</div><div class="sm f">&lt;footer&gt; patička</div></div>
      <p>Čtečky díky nim umí skočit rovnou na obsah nebo do navigace. Vzhled se nezmění — <code>header</code> se chová jako <code>div</code>.</p>` }],
    task:`Nahraď <code>div</code> s třídami <code>header</code>, <code>nav</code>, <code>main</code> a <code>footer</code> odpovídajícími sémantickými prvky. Třídy klidně nech.`,
    fixed:HTML_BASE+SEM_CSS,
    starter:`<div class="header">\n  <b>Zrnko</b>\n  <div class="nav"><a href="#">Menu</a> <a href="#">Kontakt</a></div>\n</div>\n<div class="main">\n  <h1>Káva, která voní celou ulicí</h1>\n  <p>Pražíme každý čtvrtek.</p>\n</div>\n<div class="footer">© 2026 Kavárna Zrnko</div>`,
    solution:`<header class="header">\n  <b>Zrnko</b>\n  <nav class="nav"><a href="#">Menu</a> <a href="#">Kontakt</a></nav>\n</header>\n<main class="main">\n  <h1>Káva, která voní celou ulicí</h1>\n  <p>Pražíme každý čtvrtek.</p>\n</main>\n<footer class="footer">© 2026 Kavárna Zrnko</footer>`,
    hints:["Změň název prvku v otevírací i zavírací značce: <code>&lt;div class=\"header\"&gt;</code> → <code>&lt;header class=\"header\"&gt;</code>.","Navigace je uvnitř hlavičky: <code>&lt;header&gt; … &lt;nav&gt;…&lt;/nav&gt; &lt;/header&gt;</code>."],
    checks:[
      {label:"header obsahuje nav s odkazy", test:c=>!!c.q("header nav a")},
      {label:"Právě jeden main s nadpisem", test:c=>c.qa("main").length===1&&!!c.q("main h1")},
      {label:"footer s patičkou", test:c=>/Zrnko/.test(c.text("footer"))},
      {label:"Žádné div místo sémantických prvků", test:c=>!c.q("div.header,div.nav,div.main,div.footer")} ] },
  { id:"hs-2", module:"sem", xp:180, title:"Článek a datum",
    theory:`<p><code>&lt;article&gt;</code> je samostatný kus obsahu, který dává smysl i vytržený (blogový příspěvek, karta produktu, komentář). Datum zapiš do <code>&lt;time datetime="2026-10-02"&gt;</code> — lidé čtou text, stroje atribut.</p>`,
    task:`Obal příspěvek do <code>article</code>. Datum „2. října 2026“ dej do <code>time</code> s atributem <code>datetime="2026-10-02"</code>.`,
    fixed:HTML_BASE+`article{border:1px solid #cbd5e1;border-radius:10px;padding:14px}time{color:#475569;font-size:13px}`,
    starter:`<h2>Nová sezóna kávy z Etiopie</h2>\n<p>2. října 2026</p>\n<p>Dorazila nová várka z oblasti Yirgacheffe.</p>`,
    solution:`<article>\n  <h2>Nová sezóna kávy z Etiopie</h2>\n  <p><time datetime="2026-10-02">2. října 2026</time></p>\n  <p>Dorazila nová várka z oblasti Yirgacheffe.</p>\n</article>`,
    hints:["Celé tři řádky obal do <code>&lt;article&gt;…&lt;/article&gt;</code>.","<code>&lt;time datetime=\"2026-10-02\"&gt;2. října 2026&lt;/time&gt;</code>"],
    checks:[
      {label:"article obsahuje nadpis i text", test:c=>!!c.q("article h2")&&c.qa("article p").length>=1},
      {label:"time s datetime 2026-10-02", test:c=>c.q("article time")?.getAttribute("datetime")==="2026-10-02"},
      {label:"Lidský text data zůstal", test:c=>c.text("time")==="2. října 2026"} ] },
  { id:"hs-3", module:"sem", xp:180, title:"Obrázek s popiskem",
    theory:`<p><code>&lt;figure&gt;</code> spojí obrázek (nebo graf, ukázku kódu) s jeho popiskem <code>&lt;figcaption&gt;</code>. Popisek pak patří k obrázku i pro čtečky.</p>`,
    task:`Obal obrázek a popisek do <code>figure</code> a popisek dej do <code>figcaption</code>.`,
    fixed:HTML_BASE+`figure{margin:0;border:1px solid #cbd5e1;border-radius:10px;padding:8px;max-width:280px}figcaption{font-size:13px;color:#475569;margin-top:6px}img{display:block;width:100%;height:90px;background:#8cb6c0;border-radius:6px}`,
    starter:`<img src="prazirna.jpg" alt="Pražička kávy v provozu">\n<p>Naše pražička z roku 1962.</p>`,
    solution:`<figure>\n  <img src="prazirna.jpg" alt="Pražička kávy v provozu">\n  <figcaption>Naše pražička z roku 1962.</figcaption>\n</figure>`,
    hints:["Struktura: <code>&lt;figure&gt; &lt;img&gt; &lt;figcaption&gt;…&lt;/figcaption&gt; &lt;/figure&gt;</code>","Odstavec <code>&lt;p&gt;</code> přepiš na <code>&lt;figcaption&gt;</code>."],
    checks:[
      {label:"figure obsahuje obrázek", test:c=>!!c.q("figure img[alt]")},
      {label:"figcaption s popiskem uvnitř figure", test:c=>/1962/.test(c.text("figure figcaption"))} ] },
  { id:"hs-4", module:"sem", xp:200, title:"Postranní obsah",
    theory:`<p><code>&lt;aside&gt;</code> je obsah, který s hlavním souvisí, ale není jeho součástí: související články, reklama, tip. Typicky je v postranním panelu.</p>`,
    task:`Do <code>main</code> pod článek přidej <code>aside</code> s nadpisem <b>Mohlo by vás zajímat</b> a aspoň dvěma odkazy.`,
    fixed:HTML_BASE+`aside{border-left:3px solid #c8814a;padding:4px 12px;margin-top:12px}aside a{display:block}`,
    starter:`<main>\n  <article>\n    <h1>Jak připravit filtr</h1>\n    <p>Na 250 ml vody použij 15 g kávy.</p>\n  </article>\n</main>`,
    solution:`<main>\n  <article>\n    <h1>Jak připravit filtr</h1>\n    <p>Na 250 ml vody použij 15 g kávy.</p>\n  </article>\n  <aside>\n    <h2>Mohlo by vás zajímat</h2>\n    <a href="#">Jak mlít kávu</a>\n    <a href="#">Voda na kávu</a>\n  </aside>\n</main>`,
    hints:["<code>&lt;aside&gt;</code> patří dovnitř <code>main</code>, za <code>&lt;/article&gt;</code>.","Uvnitř: <code>&lt;h2&gt;Mohlo by vás zajímat&lt;/h2&gt;</code> a dva <code>&lt;a href=\"#\"&gt;…&lt;/a&gt;</code>."],
    checks:[
      {label:"aside je uvnitř main", test:c=>!!c.q("main aside")},
      {label:"Má nadpis Mohlo by vás zajímat", test:c=>/Mohlo by vás zajímat/.test(c.text("aside h2")||c.text("aside h3"))},
      {label:"Aspoň dva odkazy s textem", test:c=>c.qa("aside a").filter(a=>a.textContent.trim().length>2).length>=2} ] },

  { id:"ht-1", module:"tab", xp:180, title:"První tabulka",
    theory:`<p>Tabulka je jen pro <b>tabulková data</b> (ceník, rozvrh), ne pro rozložení stránky. Struktura: <code>table</code> → <code>caption</code> (název) → <code>thead</code> se záhlavím <code>th</code> → <code>tbody</code> s řádky <code>tr</code> a buňkami <code>td</code>.</p>`,
    task:`Vytvoř tabulku s názvem <b>Ceník</b>, záhlavím <b>Nápoj</b> a <b>Cena</b> a třemi řádky (espresso 55 Kč, cappuccino 75 Kč, filtr 70 Kč).`,
    fixed:HTML_BASE+TABLE_CSS, starter:`<table>\n  \n</table>`,
    solution:`<table>\n  <caption>Ceník</caption>\n  <thead>\n    <tr><th>Nápoj</th><th>Cena</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Espresso</td><td>55 Kč</td></tr>\n    <tr><td>Cappuccino</td><td>75 Kč</td></tr>\n    <tr><td>Filtr</td><td>70 Kč</td></tr>\n  </tbody>\n</table>`,
    hints:["Začni <code>&lt;caption&gt;Ceník&lt;/caption&gt;</code>, pak <code>&lt;thead&gt;&lt;tr&gt;&lt;th&gt;Nápoj&lt;/th&gt;…</code>","Každý řádek je <code>&lt;tr&gt;&lt;td&gt;Espresso&lt;/td&gt;&lt;td&gt;55 Kč&lt;/td&gt;&lt;/tr&gt;</code> uvnitř <code>&lt;tbody&gt;</code>."],
    checks:[
      {label:"caption Ceník", test:c=>c.text("table caption")==="Ceník"},
      {label:"Záhlaví v thead: Nápoj, Cena", test:c=>c.qa("thead th").map(e=>e.textContent.trim()).join("|")==="Nápoj|Cena"},
      {label:"3 řádky v tbody po 2 buňkách", test:c=>{const r=c.qa("tbody tr");return r.length===3&&r.every(x=>x.querySelectorAll("td,th").length===2)}} ] },
  { id:"ht-2", module:"tab", xp:200, title:"Záhlaví řádků",
    theory:`<p>Když má tabulka popisky i v prvním sloupci (třeba dny v rozvrhu), jsou to také <code>th</code>. Atribut <code>scope</code> říká, k čemu patří: <code>scope="col"</code> pro sloupec, <code>scope="row"</code> pro řádek. Čtečka pak u každé buňky přečte „Pondělí, Otevírací doba: 7:30–18:00“.</p>`,
    task:`V tabulce otevírací doby udělej z dnů v prvním sloupci <code>th scope="row"</code> a záhlaví sloupců označ <code>scope="col"</code>.`,
    fixed:HTML_BASE+TABLE_CSS+`tbody th{text-align:left}`,
    starter:`<table>\n  <thead>\n    <tr><th>Den</th><th>Otevřeno</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Pondělí</td><td>7:30–18:00</td></tr>\n    <tr><td>Sobota</td><td>9:00–16:00</td></tr>\n    <tr><td>Neděle</td><td>zavřeno</td></tr>\n  </tbody>\n</table>`,
    solution:`<table>\n  <thead>\n    <tr><th scope="col">Den</th><th scope="col">Otevřeno</th></tr>\n  </thead>\n  <tbody>\n    <tr><th scope="row">Pondělí</th><td>7:30–18:00</td></tr>\n    <tr><th scope="row">Sobota</th><td>9:00–16:00</td></tr>\n    <tr><th scope="row">Neděle</th><td>zavřeno</td></tr>\n  </tbody>\n</table>`,
    hints:["V <code>tbody</code> změň první <code>&lt;td&gt;</code> v každém řádku na <code>&lt;th scope=\"row\"&gt;</code>.","V <code>thead</code> přidej oběma <code>th</code> atribut <code>scope=\"col\"</code>."],
    checks:[
      {label:"Dny jsou th scope=row", test:c=>{const r=c.qa("tbody tr");return r.length===3&&r.every(x=>x.firstElementChild?.localName==="th"&&x.firstElementChild.getAttribute("scope")==="row")}},
      {label:"Záhlaví sloupců má scope=col", test:c=>{const t=c.qa("thead th");return t.length===2&&t.every(x=>x.getAttribute("scope")==="col")}} ] },

  { id:"hf-1", module:"form", xp:220, title:"Popisek k poli",
    slides:[{ title:"Každé pole potřebuje popisek", html:`<p>Placeholder (šedý text v poli) není popisek — zmizí, jakmile začneš psát, a čtečky ho často nepřečtou. Správně je <code>&lt;label&gt;</code> propojený s polem:</p><pre class="mini">&lt;label for="jmeno"&gt;Jméno&lt;/label&gt;\n&lt;input id="jmeno"&gt;</pre><p><code>for</code> u labelu = <code>id</code> u pole. Bonus: kliknutí na popisek přesune kurzor do pole — větší cíl pro myš i prst.</p>` }],
    task:`Pole pro jméno má jen placeholder. Přidej mu <code>label</code> s textem <b>Jméno</b> propojený přes <code>for</code> a <code>id</code>.`,
    fixed:HTML_BASE+FORM_CSS, starter:`<form>\n  <input placeholder="Jan Novák">\n</form>`,
    solution:`<form>\n  <label for="jmeno">Jméno</label>\n  <input id="jmeno" placeholder="Jan Novák">\n</form>`,
    hints:["Poli dej <code>id=\"jmeno\"</code>, labelu <code>for=\"jmeno\"</code>.","<code>&lt;label for=\"jmeno\"&gt;Jméno&lt;/label&gt;</code> nad <code>&lt;input id=\"jmeno\" …&gt;</code>"],
    checks:[
      {label:"Label s textem Jméno", test:c=>/^Jméno/.test(c.text("label"))},
      {label:"Label je propojený s polem", test:c=>{const i=c.q("input");return !!i&&(i.labels?.length>0)}} ] },
  { id:"hf-2", module:"form", xp:220, title:"Správný typ pole",
    theory:`<p>Atribut <code>type</code> mění chování pole: <code>email</code> zkontroluje zavináč a na mobilu ukáže klávesnici s @, <code>tel</code> číselnou klávesnici, <code>number</code> šipky a meze <code>min</code>/<code>max</code>. Uživatel dostane lepší klávesnici, ty méně chyb.</p>`,
    task:`Nastav správné typy: e-mail → <code>email</code>, telefon → <code>tel</code>, počet osob → <code>number</code> s rozsahem 1 až 10.`,
    fixed:HTML_BASE+FORM_CSS,
    starter:`<form>\n  <label for="email">E-mail</label>\n  <input id="email">\n  <label for="tel">Telefon</label>\n  <input id="tel">\n  <label for="osoby">Počet osob</label>\n  <input id="osoby">\n</form>`,
    solution:`<form>\n  <label for="email">E-mail</label>\n  <input id="email" type="email">\n  <label for="tel">Telefon</label>\n  <input id="tel" type="tel">\n  <label for="osoby">Počet osob</label>\n  <input id="osoby" type="number" min="1" max="10">\n</form>`,
    hints:["Přidej atribut <code>type</code> do každého <code>&lt;input&gt;</code>.","Počet osob: <code>type=\"number\" min=\"1\" max=\"10\"</code>"],
    checks:[
      {label:"E-mail: type=email", test:c=>c.q("#email")?.type==="email"},
      {label:"Telefon: type=tel", test:c=>c.q("#tel")?.type==="tel"},
      {label:"Počet osob: number 1–10", test:c=>{const i=c.q("#osoby");return i?.type==="number"&&i.min==="1"&&i.max==="10"}} ] },
  { id:"hf-3", module:"form", xp:240, title:"Povinné pole a nápověda",
    theory:`<p><code>required</code> nedovolí formulář odeslat bez vyplnění. <code>autocomplete="email"</code> nabídne uložený e-mail — o polovinu méně psaní. Nápovědu k poli propojíš přes <code>aria-describedby</code> s <code>id</code> textu: čtečka ji přečte spolu s popiskem.</p>`,
    task:`Pole e-mailu udělej povinné, zapni mu <code>autocomplete="email"</code> a propoj ho s nápovědou <code>#email-tip</code> přes <code>aria-describedby</code>.`,
    fixed:HTML_BASE+FORM_CSS+`.tip{font-size:13px;color:#475569;margin:-4px 0 0}`,
    starter:`<form>\n  <label for="email">E-mail</label>\n  <input id="email" type="email">\n  <p class="tip" id="email-tip">Pošleme jen potvrzení rezervace.</p>\n</form>`,
    solution:`<form>\n  <label for="email">E-mail</label>\n  <input id="email" type="email" required autocomplete="email" aria-describedby="email-tip">\n  <p class="tip" id="email-tip">Pošleme jen potvrzení rezervace.</p>\n</form>`,
    hints:["Tři atributy navíc: <code>required</code>, <code>autocomplete</code>, <code>aria-describedby</code>.","<code>aria-describedby=\"email-tip\"</code> — hodnota je id nápovědy bez mřížky."],
    checks:[
      {label:"Pole je povinné", test:c=>c.q("#email")?.required===true},
      {label:"autocomplete=email", test:c=>c.q("#email")?.getAttribute("autocomplete")==="email"},
      {label:"Nápověda propojená přes aria-describedby", test:c=>(c.q("#email")?.getAttribute("aria-describedby")||"").split(/\s+/).includes("email-tip")} ] },
  { id:"hf-4", module:"form", xp:240, title:"Výběr jedné možnosti",
    theory:`<p>Přepínače <code>type="radio"</code> se stejným <code>name</code> tvoří skupinu — vybrat jde jen jeden. Skupinu obal do <code>&lt;fieldset&gt;</code> a otázku dej do <code>&lt;legend&gt;</code>. Každý přepínač potřebuje vlastní label — nejjednodušší je dát input <i>dovnitř</i> labelu.</p>`,
    task:`Vytvoř skupinu <b>Velikost kávy</b> (fieldset + legend) se třemi přepínači <code>name="velikost"</code>: Malá, Střední, Velká.`,
    fixed:HTML_BASE+FORM_CSS+`fieldset{border:1px solid #cbd5e1;border-radius:8px;display:grid;gap:6px}legend{font-weight:700;padding:0 4px}fieldset label{display:flex;gap:6px;font-weight:400;align-items:center}`,
    starter:`<form>\n  \n</form>`,
    solution:`<form>\n  <fieldset>\n    <legend>Velikost kávy</legend>\n    <label><input type="radio" name="velikost" value="mala"> Malá</label>\n    <label><input type="radio" name="velikost" value="stredni"> Střední</label>\n    <label><input type="radio" name="velikost" value="velka"> Velká</label>\n  </fieldset>\n</form>`,
    hints:["Kostra: <code>&lt;fieldset&gt;&lt;legend&gt;Velikost kávy&lt;/legend&gt; … &lt;/fieldset&gt;</code>","Přepínač: <code>&lt;label&gt;&lt;input type=\"radio\" name=\"velikost\"&gt; Malá&lt;/label&gt;</code>"],
    checks:[
      {label:"fieldset s legend Velikost kávy", test:c=>c.text("fieldset legend")==="Velikost kávy"},
      {label:"3 přepínače se stejným name", test:c=>{const r=c.qa("fieldset input[type=radio]");return r.length===3&&r.every(x=>x.name==="velikost")}},
      {label:"Každý přepínač má popisek Malá / Střední / Velká", test:c=>c.qa("input[type=radio]").map(x=>x.labels?.[0]?.textContent.trim()).join("|")==="Malá|Střední|Velká"} ] },
  { id:"hf-5", module:"form", xp:260, title:"Výběr, zpráva a odeslání",
    theory:`<p><code>&lt;select&gt;</code> s <code>&lt;option&gt;</code> = rozbalovací seznam, <code>&lt;textarea&gt;</code> = víceřádkový text. Odesílací tlačítko je <code>&lt;button type="submit"&gt;</code> s textem, který říká, co se stane („Odeslat rezervaci“, ne „OK“).</p>`,
    task:`Doplň formulář: výběr <b>Pobočka</b> (Brno, Praha), textové pole <b>Poznámka</b> a tlačítko <b>Odeslat rezervaci</b> typu submit. Pole mají mít labely.`,
    fixed:HTML_BASE+FORM_CSS, starter:`<form>\n  \n</form>`,
    solution:`<form>\n  <label for="pobocka">Pobočka</label>\n  <select id="pobocka">\n    <option>Brno</option>\n    <option>Praha</option>\n  </select>\n  <label for="pozn">Poznámka</label>\n  <textarea id="pozn"></textarea>\n  <button type="submit">Odeslat rezervaci</button>\n</form>`,
    hints:["<code>&lt;select id=\"pobocka\"&gt;&lt;option&gt;Brno&lt;/option&gt;…&lt;/select&gt;</code> a nad ním <code>&lt;label for=\"pobocka\"&gt;</code>.","Na konec <code>&lt;button type=\"submit\"&gt;Odeslat rezervaci&lt;/button&gt;</code>."],
    checks:[
      {label:"select Pobočka s Brnem a Prahou", test:c=>{const s=c.q("select");return !!s&&s.labels?.[0]?.textContent.trim()==="Pobočka"&&[...s.options].map(o=>o.textContent.trim()).join("|")==="Brno|Praha"}},
      {label:"textarea s popiskem Poznámka", test:c=>c.q("textarea")?.labels?.[0]?.textContent.trim()==="Poznámka"},
      {label:"Tlačítko submit: Odeslat rezervaci", test:c=>{const b=c.q("button");return b?.type==="submit"&&c.text("button")==="Odeslat rezervaci"}} ] },

  { id:"ha-1", module:"a11y", xp:240, kind:"debug", title:"Tlačítko, ne div",
    theory:`<p><code>&lt;div&gt;</code> s kliknutím vypadá jako tlačítko, ale nedá se na něj dostat klávesnicí (Tab), nejde zmáčknout Enterem ani mezerníkem a čtečka neví, že je to tlačítko. <code>&lt;button type="button"&gt;</code> tohle všechno umí zadarmo.</p>`,
    task:`„Tlačítko“ Přidat do košíku je <code>div</code>. Udělej z něj skutečné tlačítko <code>button</code> typu <code>button</code>. Třídu nech.`,
    fixed:HTML_BASE+`.btn{display:inline-block;background:#2f5bd3;color:#fff;border:0;padding:10px 16px;border-radius:8px;font:inherit;font-weight:700;cursor:pointer}`,
    starter:`<div class="btn">Přidat do košíku</div>`, solution:`<button type="button" class="btn">Přidat do košíku</button>`,
    hints:["Přepiš <code>div</code> na <code>button</code> v otevírací i zavírací značce.","<code>&lt;button type=\"button\" class=\"btn\"&gt;Přidat do košíku&lt;/button&gt;</code>"],
    checks:[
      {label:"Je to button s textem Přidat do košíku", test:c=>c.text("button")==="Přidat do košíku"},
      {label:"type=button", test:c=>c.q("button")?.getAttribute("type")==="button"},
      {label:"Žádný div.btn", test:c=>!c.q("div.btn")} ] },
  { id:"ha-2", module:"a11y", xp:240, title:"Ikona bez textu",
    theory:`<p>Tlačítko jen s ikonou (×, lupa, hamburger) nemá pro čtečku žádný název — přečte „tlačítko“ a nic víc. Pojmenuj ho přes <code>aria-label</code>. Samotnou ikonu schovej před čtečkou: <code>aria-hidden="true"</code>.</p>`,
    task:`Zavírací tlačítko s ikonou × pojmenuj <b>Zavřít</b> přes <code>aria-label</code> a ikonu <code>span</code> schovej přes <code>aria-hidden="true"</code>.`,
    fixed:HTML_BASE+`.close{width:36px;height:36px;border-radius:50%;border:1px solid #cbd5e1;background:#fff;font-size:20px;cursor:pointer}`,
    starter:`<button type="button" class="close"><span>×</span></button>`, solution:`<button type="button" class="close" aria-label="Zavřít"><span aria-hidden="true">×</span></button>`,
    hints:["Tlačítku přidej <code>aria-label=\"Zavřít\"</code>.","Ikoně <code>&lt;span aria-hidden=\"true\"&gt;×&lt;/span&gt;</code>."],
    checks:[
      {label:"Tlačítko má název Zavřít", test:c=>c.q("button")?.getAttribute("aria-label")==="Zavřít"},
      {label:"Ikona je skrytá před čtečkou", test:c=>c.q("button span")?.getAttribute("aria-hidden")==="true"} ] },
  { id:"ha-3", module:"a11y", xp:240, kind:"debug", title:"Odkaz, který dává smysl",
    theory:`<p>Čtečky umí vypsat všechny odkazy na stránce bez okolního textu. Seznam „klikni zde, klikni zde, více“ je k ničemu. Text odkazu má sám říct, kam vede.</p>`,
    task:`Přepiš větu tak, aby odkazem byl text <b>ceník kávy</b>, ne „klikni zde“. Odkaz vede na <code>/cenik</code>.`,
    fixed:HTML_BASE, starter:`<p>Náš ceník kávy najdete, když <a href="/cenik">klikni zde</a>.</p>`, solution:`<p>Podívejte se na náš <a href="/cenik">ceník kávy</a>.</p>`,
    hints:["Odkazem obal slova, která popisují cíl.","<code>&lt;a href=\"/cenik\"&gt;ceník kávy&lt;/a&gt;</code>"],
    checks:[
      {label:"Odkaz vede na /cenik", test:c=>c.q("a")?.getAttribute("href")==="/cenik"},
      {label:"Text odkazu je ceník kávy", test:c=>/ceník kávy/i.test(c.text("a"))},
      {label:"Žádné „klikni zde“", test:c=>!/klikni zde|zde|více/i.test(c.text("a"))} ] },
  { id:"ha-4", module:"a11y", xp:240, title:"Jazyk a dekorace",
    theory:`<p>Čtečka čte podle jazyka. Cizojazyčný citát označ atributem <code>lang</code> (<code>lang="en"</code>), jinak ho přečte s českou výslovností. Čistě dekorativní obrázek (ornament, oddělovač) má mít <b>prázdný</b> <code>alt=""</code> — čtečka ho přeskočí.</p>`,
    task:`Anglický citát v <code>blockquote</code> označ <code>lang="en"</code> a dekorativnímu ornamentu <code>img.ornament</code> dej prázdný alt.`,
    fixed:HTML_BASE+`blockquote{margin:8px 0;padding-left:12px;border-left:3px solid #8cb6c0;font-style:italic}.ornament{display:block;width:60px;height:8px;background:#c8814a;border-radius:4px}`,
    starter:`<img class="ornament" src="ornament.svg">\n<blockquote>Coffee is a language in itself.</blockquote>\n<p>— Jackie Chan</p>`,
    solution:`<img class="ornament" src="ornament.svg" alt="">\n<blockquote lang="en">Coffee is a language in itself.</blockquote>\n<p>— Jackie Chan</p>`,
    hints:["<code>&lt;blockquote lang=\"en\"&gt;</code>","Ornament: <code>alt=\"\"</code> — atribut tam být musí, jen prázdný."],
    checks:[
      {label:"Citát má lang=en", test:c=>c.q("blockquote")?.getAttribute("lang")==="en"},
      {label:"Ornament má prázdný alt", test:c=>{const i=c.q("img.ornament");return !!i&&i.hasAttribute("alt")&&i.getAttribute("alt")===""}} ] },

  { id:"hm-1", module:"modern", xp:260, support:{status:"baseline"}, title:"Rozbalovací FAQ bez JS",
    theory:`<p><code>&lt;details&gt;</code> se <code>&lt;summary&gt;</code> je hotový rozbalovací prvek: funguje klávesnicí, čtečka ví, jestli je otevřený, a nepotřebuje ani řádek JavaScriptu. Atribut <code>name</code> se stejnou hodnotou udělá z více details akordeon — otevřený může být jen jeden.</p>`,
    task:`Udělej dvě otázky jako <code>details</code> se <code>summary</code>: <b>Máte rostlinné mléko?</b> (Ano, ovesné i mandlové.) a <b>Můžu přijít se psem?</b> (Jasně, máme i misku s vodou.). Spoj je do akordeonu přes <code>name="faq"</code>.`,
    fixed:HTML_BASE+`details{border:1px solid #cbd5e1;border-radius:8px;padding:8px 12px;margin-bottom:6px}summary{font-weight:700;cursor:pointer}`,
    starter:`<h2>Časté dotazy</h2>\n`,
    solution:`<h2>Časté dotazy</h2>\n<details name="faq">\n  <summary>Máte rostlinné mléko?</summary>\n  <p>Ano, ovesné i mandlové.</p>\n</details>\n<details name="faq">\n  <summary>Můžu přijít se psem?</summary>\n  <p>Jasně, máme i misku s vodou.</p>\n</details>`,
    hints:["Kostra: <code>&lt;details&gt;&lt;summary&gt;Otázka&lt;/summary&gt;&lt;p&gt;Odpověď&lt;/p&gt;&lt;/details&gt;</code>","Oběma details přidej <code>name=\"faq\"</code>."],
    checks:[
      {label:"Dvě details se summary", test:c=>{const d=c.qa("details");return d.length===2&&d.every(x=>x.querySelector("summary"))}},
      {label:"Otázky sedí", test:c=>c.qa("summary").map(s=>s.textContent.trim()).join("|")==="Máte rostlinné mléko?|Můžu přijít se psem?"},
      {label:"Akordeon: obě mají name=faq", test:c=>c.qa("details").every(x=>x.getAttribute("name")==="faq")} ] },
  { id:"hm-2", module:"modern", xp:260, title:"Dialog",
    theory:`<p><code>&lt;dialog&gt;</code> je nativní modální okno: drží fokus uvnitř, zavře se klávesou Esc a čtečka ho ohlásí. Otevírá se JavaScriptem (<code>showModal()</code>), pro náhled stačí atribut <code>open</code>. Tlačítko uvnitř <code>&lt;form method="dialog"&gt;</code> dialog zavře bez JS.</p>`,
    task:`Vytvoř otevřený <code>dialog</code> s nadpisem <b>Smazat rezervaci?</b> a formulářem <code>method="dialog"</code> s tlačítkem <b>Zrušit</b>.`,
    fixed:HTML_BASE+`dialog{position:static;border:1px solid #cbd5e1;border-radius:12px;padding:16px;box-shadow:0 8px 24px #0002}dialog h2{margin:0 0 10px;font-size:18px}`,
    starter:``, solution:`<dialog open>\n  <h2>Smazat rezervaci?</h2>\n  <form method="dialog">\n    <button>Zrušit</button>\n  </form>\n</dialog>`,
    hints:["<code>&lt;dialog open&gt; … &lt;/dialog&gt;</code>","Uvnitř <code>&lt;form method=\"dialog\"&gt;&lt;button&gt;Zrušit&lt;/button&gt;&lt;/form&gt;</code>"],
    checks:[
      {label:"dialog s atributem open", test:c=>c.q("dialog")?.hasAttribute("open")},
      {label:"Nadpis Smazat rezervaci?", test:c=>/Smazat rezervaci\?/.test(c.text("dialog h2")||c.text("dialog h1")||c.text("dialog h3"))},
      {label:"form method=dialog s tlačítkem Zrušit", test:c=>c.q("dialog form")?.getAttribute("method")==="dialog"&&/Zrušit/.test(c.text("dialog form button"))} ] },
  { id:"hm-3", module:"modern", xp:280, support:{status:"baseline"}, title:"Popover bez JavaScriptu",
    theory:`<p>Atribut <code>popover</code> udělá z prvku vyskakovací okno nad stránkou (zavře se klikem mimo nebo Esc). Tlačítko ho otevře přes <code>popovertarget</code> s <code>id</code> popoveru. Menu, nápovědy a výběry bez jediného skriptu.</p>`,
    task:`Tlačítko <b>Alergeny</b> má otevírat popover s <code>id="alergeny"</code>. Doplň atributy. Zkus pak na tlačítko kliknout.`,
    fixed:HTML_BASE+`[popover]{border:1px solid #cbd5e1;border-radius:10px;padding:12px;box-shadow:0 8px 24px #0002}button{font:inherit;padding:6px 12px;border-radius:6px;border:1px solid #94a3b8;background:#fff;cursor:pointer}`,
    starter:`<button>Alergeny</button>\n<div>Obsahuje mléko a lepek.</div>`, solution:`<button popovertarget="alergeny">Alergeny</button>\n<div id="alergeny" popover>Obsahuje mléko a lepek.</div>`,
    hints:["Div: <code>id=\"alergeny\" popover</code>.","Tlačítko: <code>popovertarget=\"alergeny\"</code>."],
    checks:[
      {label:"Div je popover s id alergeny", test:c=>{const d=c.q("#alergeny");return !!d&&d.hasAttribute("popover")}},
      {label:"Tlačítko ho otevírá", test:c=>c.q("button")?.getAttribute("popovertarget")==="alergeny"} ] },
  { id:"hm-4", module:"modern", xp:280, title:"Responzivní obrázek",
    theory:`<p><code>&lt;picture&gt;</code> nabídne prohlížeči víc verzí obrázku: <code>&lt;source media="(min-width: 800px)" srcset="velky.jpg"&gt;</code> pro širokou obrazovku, uvnitř vždy <code>&lt;img&gt;</code> jako výchozí s altem. <code>loading="lazy"</code> načte obrázek, až když se k němu uživatel doroluje — rychlejší stránka zadarmo.</p>`,
    task:`Vytvoř <code>picture</code>: na obrazovkách od 800px se použije <code>hero-velky.jpg</code>, jinak <code>hero-maly.jpg</code> s alt textem. Obrázek načítej líně.`,
    fixed:HTML_BASE, starter:``,
    solution:`<picture>\n  <source media="(min-width: 800px)" srcset="hero-velky.jpg">\n  <img src="hero-maly.jpg" alt="Barista nalévá latte art" loading="lazy">\n</picture>`,
    hints:["Kostra: <code>&lt;picture&gt; &lt;source …&gt; &lt;img …&gt; &lt;/picture&gt;</code>","<code>&lt;source media=\"(min-width: 800px)\" srcset=\"hero-velky.jpg\"&gt;</code> a img s <code>loading=\"lazy\"</code>."],
    checks:[
      {label:"source pro (min-width: 800px) s hero-velky.jpg", test:c=>{const s=c.q("picture source");return !!s&&/min-width:\s*800px/.test(s.getAttribute("media")||"")&&s.getAttribute("srcset")==="hero-velky.jpg"}},
      {label:"img hero-maly.jpg s altem", test:c=>{const i=c.q("picture img");return i?.getAttribute("src")==="hero-maly.jpg"&&(i.getAttribute("alt")||"").trim().length>3}},
      {label:"loading=lazy", test:c=>c.q("picture img")?.getAttribute("loading")==="lazy"} ] },

  { id:"hb-1", module:"hboss", xp:600, boss:true, wide:true, title:"Div polévka",
    theory:`<p>Projekt z praxe: kolega postavil stránku jen z <code>div</code> a <code>span</code>. Vypadá dobře, ale čtečky, vyhledávače i klávesnice jsou ztracené. Přepiš ji sémanticky — vzhled zůstane stejný, protože CSS je navázané na třídy.</p>`,
    task:`1) <code>header</code> s <code>nav</code>, <code>main</code>, <code>footer</code><br>2) jeden <code>h1</code>, sekce s <code>h2</code><br>3) produkty jako <code>article</code><br>4) obrázky s altem<br>5) „tlačítka“ jako <code>button</code><br>6) pole newsletteru s <code>label</code> a <code>type="email"</code>`,
    fixed:HTML_BASE+`.top{display:flex;justify-content:space-between;align-items:center;background:#14203a;color:#fff;padding:10px 14px;border-radius:10px}.top a{color:#fff;margin-left:12px}.logo{font-weight:800}.title{font-size:24px;font-weight:800;margin:14px 0 4px}.sub{font-size:17px;font-weight:700;margin:14px 0 6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.prod{border:1px solid #cbd5e1;border-radius:10px;padding:10px}.prod img{display:block;width:100%;height:60px;background:#f3b184;border-radius:6px}.name{font-weight:700;display:block;margin-top:6px}.btn{display:inline-block;margin-top:6px;background:#2f5bd3;color:#fff;border:0;border-radius:6px;padding:6px 10px;font:inherit;font-size:13px;cursor:pointer}.foot{margin-top:14px;padding-top:10px;border-top:1px solid #cbd5e1;font-size:13px}.nl{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.nl input{padding:6px;border:1px solid #94a3b8;border-radius:6px}`,
    starter:`<div class="top">\n  <span class="logo">Kolo</span>\n  <div class="menu"><a href="#">Kola</a><a href="#">Servis</a><a href="#">Kontakt</a></div>\n</div>\n<div class="content">\n  <div class="title">Městská kola z Prahy</div>\n  <div class="sub">Novinky</div>\n  <div class="grid">\n    <div class="prod">\n      <img src="kolo1.jpg">\n      <span class="name">Kolo 01 Městák</span>\n      <div class="btn">Do košíku</div>\n    </div>\n    <div class="prod">\n      <img src="kolo2.jpg">\n      <span class="name">Kolo 02 Skládačka</span>\n      <div class="btn">Do košíku</div>\n    </div>\n  </div>\n</div>\n<div class="foot">\n  <div class="nl">Newsletter <input placeholder="vas@email.cz"> <div class="btn">Odebírat</div></div>\n</div>`,
    solution:`<header class="top">\n  <span class="logo">Kolo</span>\n  <nav class="menu"><a href="#">Kola</a><a href="#">Servis</a><a href="#">Kontakt</a></nav>\n</header>\n<main class="content">\n  <h1 class="title">Městská kola z Prahy</h1>\n  <section>\n    <h2 class="sub">Novinky</h2>\n    <div class="grid">\n      <article class="prod">\n        <img src="kolo1.jpg" alt="Žluté městské kolo s košíkem">\n        <h3 class="name">Kolo 01 Městák</h3>\n        <button type="button" class="btn">Do košíku</button>\n      </article>\n      <article class="prod">\n        <img src="kolo2.jpg" alt="Modré skládací kolo složené vedle tašky">\n        <h3 class="name">Kolo 02 Skládačka</h3>\n        <button type="button" class="btn">Do košíku</button>\n      </article>\n    </div>\n  </section>\n</main>\n<footer class="foot">\n  <form class="nl">\n    <label for="nl-email">Newsletter</label>\n    <input id="nl-email" type="email" placeholder="vas@email.cz">\n    <button type="submit" class="btn">Odebírat</button>\n  </form>\n</footer>`,
    hints:["Postupuj shora: <code>div.top</code> → <code>header</code>, <code>div.menu</code> → <code>nav</code>, <code>div.content</code> → <code>main</code>, <code>div.foot</code> → <code>footer</code>. Třídy nech.","Produkty: <code>&lt;article class=\"prod\"&gt;</code>, název jako <code>&lt;h3&gt;</code>, „tlačítka“ jako <code>&lt;button&gt;</code>. Newsletter obal do <code>&lt;form&gt;</code> s <code>&lt;label for&gt;</code>."],
    checks:[
      {group:"Kostra", label:"header s nav, main, footer", test:c=>!!c.q("header nav a")&&c.qa("main").length===1&&!!c.q("footer")},
      {group:"Nadpisy", label:"Jeden h1, sekce s h2", test:c=>c.qa("h1").length===1&&!!c.q("main h2")},
      {group:"Nadpisy", label:"Nadpisy nepřeskakují úrovně", test:c=>{let last=0;for(const h of c.qa("h1,h2,h3,h4,h5,h6")){const n=+h.localName[1];if(n>last+1)return false;last=n}return true}},
      {group:"Obsah", label:"Produkty jsou article", test:c=>c.qa("article").length===2},
      {group:"Obsah", label:"Obrázky mají popisný alt", test:c=>c.qa("img").length===2&&c.qa("img").every(i=>(i.getAttribute("alt")||"").trim().split(/\s+/).length>=3)},
      {group:"Ovládání", label:"Všechna „tlačítka“ jsou button", test:c=>c.qa("button").length===3&&!c.q("div.btn")},
      {group:"Formulář", label:"Pole newsletteru: label + type=email", test:c=>{const i=c.q("footer input");return i?.type==="email"&&i.labels?.length>0}} ] },
  ],
  achievements:[
    {id:"html-base", name:"Stavitel stránek", desc:"Dokonči modul Základy HTML.", glyph:"<>", color:"var(--c-html)", test:(s,cs)=>moduleDone(cs,"html","base")},
    {id:"html-sem",  name:"Kartograf", desc:"Dokonči modul Sémantika.", glyph:"§", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"html","sem")},
    {id:"html-tab",  name:"Tabulkář", desc:"Dokonči modul Tabulky.", glyph:"▦", color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"html","tab")},
    {id:"html-form", name:"Formulářník", desc:"Dokonči modul Formuláře.", glyph:"[_]", color:"var(--m-border)", test:(s,cs)=>moduleDone(cs,"html","form")},
    {id:"html-a11y", name:"Pro všechny", desc:"Dokonči modul Přístupnost.", glyph:"♿", color:"var(--m-margin)", test:(s,cs)=>moduleDone(cs,"html","a11y")},
    {id:"html-modern",name:"Nativák", desc:"Dokonči modul Moderní HTML.", glyph:"✦", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"html","modern")},
    {id:"html-soup", name:"Kuchař sémantiky", desc:"Přepiš Div polévku.", glyph:"★", color:"var(--accent)", test:(s,cs)=>!!cs.done["hb-1"]},
  ]
});
