/* ----------------------------- JavaScript -----------------------------
   engine "js"  = kód běží ve Web Workeru, testy jsou výrazy (smí vracet Promise)
   engine "dom" = kód běží v izolovaném iframu nad L.html; test smí mít "act" (kliknutí, vyplnění) před výrazem.
   L.prelude    = připravený kód, který běží před hráčovým (data, falešné API). */
const DOM_CSS=`button{font:inherit;font-weight:700;padding:7px 12px;border-radius:8px;border:0;background:#2f5bd3;color:#fff;cursor:pointer}input{font:inherit;padding:7px 10px;border:1px solid #94a3b8;border-radius:8px}ul{padding-left:20px}`;
const FAKE_USERS=`// falešná databáze — odpovídá po 30 ms jako skutečný server
const UZIVATELE = { 1: { id: 1, jmeno: "Ada" }, 2: { id: 2, jmeno: "Linus" } };
function nactiUzivatele(id) {
  return new Promise((ok, chyba) => setTimeout(() => {
    if (UZIVATELE[id]) ok(UZIVATELE[id]);
    else chyba(new Error("Uživatel " + id + " neexistuje"));
  }, 30));
}`;

registerCourse({ id:"js", name:"JavaScript", tagline:"Od první proměnné po DOM, async a moderní JS", color:"var(--c-js)", engine:"js", status:"live", code:"const x = 1;",
  tiers:[
    { id:"junior", name:"Junior", desc:"Proměnné, text a čísla, funkce, podmínky, pole a cykly.", glyph:"JR" },
    { id:"medior", name:"Medior", desc:"Metody polí, objekty, JSON a práce se stránkou (DOM, události, formuláře).", glyph:"MD" },
    { id:"senior", name:"Senior", desc:"Promise a async/await, fetch, moderní syntaxe, uzávěry, třídy a projekt z praxe.", glyph:"SR" },
  ],
  modules:[
    { id:"zak",   tier:"junior", name:"Proměnné a hodnoty", sub:"let, const, text, čísla, typeof", color:"var(--c-js)", glyph:"x=" },
    { id:"fn",    tier:"junior", name:"Funkce a logika", sub:"return, podmínky, šipky, výchozí hodnoty", color:"var(--m-content)", glyph:"f()" },
    { id:"loop",  tier:"junior", name:"Pole a cykly", sub:"for…of, push, includes, počítání", color:"var(--m-padding)", glyph:"[ ]" },
    { id:"arr",   tier:"medior", name:"Metody polí", sub:"map, filter, find, reduce, sort", color:"var(--m-border)", glyph:".map" },
    { id:"obj",   tier:"medior", name:"Objekty a JSON", sub:"vlastnosti, destrukturování, spread, JSON", color:"var(--m-margin)", glyph:"{ }" },
    { id:"dom",   tier:"medior", name:"Práce se stránkou", sub:"querySelector, classList, události, formuláře", color:"var(--c-js)", glyph:"$" },
    { id:"async", tier:"senior", name:"Asynchronní JS", sub:"Promise, async/await, try/catch, Promise.all, fetch", color:"var(--m-content)", glyph:"⏳" },
    { id:"modern",tier:"senior", name:"Moderní JS", sub:"?. a ??, Set, uzávěry, neměnné úpravy, třídy", color:"var(--m-padding)", glyph:"✦" },
    { id:"jboss", tier:"senior", name:"Projekt z praxe", sub:"Kavárenský košík: data, události a vykreslení", color:"var(--accent)", glyph:"★" },
  ],
  levels:[
  /* ======================= PROMĚNNÉ A HODNOTY ======================= */
  { id:"j-0a", module:"zak", xp:100, title:"Proměnné",
    slides:[
      { title:"Co tu děláš", html:`<p>JavaScript dává stránkám chování: reaguje na kliknutí, počítá, načítá data. V editoru píšeš kód a pod ním vidíš <b>Testy</b> — kontroly, které tvůj kód zkouší. Až budou všechny zelené, odevzdáš.</p><p>Do <b>Konzole</b> si můžeš cokoliv vypsat přes <code>console.log(…)</code>. Hodí se to, když nevíš, co se v kódu děje.</p>` },
      { title:"Proměnná = pojmenovaná krabička", html:`<pre class="mini">const jmeno = "Ada";   // nezmění se\nlet vek = 36;          // může se měnit\nvek = vek + 1;         // teď je 37</pre><p><code>const</code> používej jako výchozí. <code>let</code> jen když hodnotu budeš přepisovat. Text patří do uvozovek, čísla ne.</p>` } ],
    task:`Vytvoř konstantu <code>jmeno</code> s textem <code>"Ada"</code> a proměnnou <code>vek</code> s číslem <code>36</code>. Na dalším řádku <code>vek</code> zvyš o 1.`,
    starter:`// sem napiš proměnné\n\nconsole.log(jmeno, vek);`,
    solution:`const jmeno = "Ada";\nlet vek = 36;\nvek = vek + 1;\n\nconsole.log(jmeno, vek);`,
    hints:["<code>const jmeno = \"Ada\";</code> a <code>let vek = 36;</code>","Zvýšení: <code>vek = vek + 1;</code> (nebo zkráceně <code>vek++</code>)."],
    tests:[{label:"jmeno je \"Ada\"",expr:"jmeno",expect:"Ada"},{label:"vek je po zvýšení 37",expr:"vek",expect:37}] },
  { id:"j-0b", module:"zak", xp:110, title:"Text se šablonou",
    theory:`<p>Text v <b>zpětných apostrofech</b> <code>\`…\`</code> je šablona: hodnotu do něj vložíš přes <code>\${…}</code>.</p><pre class="mini">const zbozi = "káva";\n\`Do košíku jsi přidal \${zbozi}.\`</pre><p>Je to přehlednější než lepení přes <code>+</code>: <code>"Do košíku jsi přidal " + zbozi + "."</code></p>`,
    task:`Doplň funkci <code>pozdrav(jmeno)</code>, aby vrátila text <code>Ahoj, Ada!</code> (pro jméno Ada). Použij šablonu.`,
    starter:`function pozdrav(jmeno) {\n  return "Ahoj";\n}\n\nconsole.log(pozdrav("Ada"));`,
    solution:`function pozdrav(jmeno) {\n  return \`Ahoj, \${jmeno}!\`;\n}\n\nconsole.log(pozdrav("Ada"));`,
    hints:["Zpětný apostrof na české klávesnici: pravý Alt + ý, na Macu klávesa vlevo od Z (nebo ` vedle Enteru).","<code>return \`Ahoj, \${jmeno}!\`;</code>"],
    tests:[{label:"pozdrav(\"Ada\") → \"Ahoj, Ada!\"",expr:"pozdrav(\"Ada\")",expect:"Ahoj, Ada!"},{label:"pozdrav(\"Petr\") → \"Ahoj, Petr!\"",expr:"pozdrav(\"Petr\")",expect:"Ahoj, Petr!"}] },
  { id:"j-0c", module:"zak", xp:130, kind:"debug", title:"Čísla, která jsou text",
    theory:`<p>Hodnoty z formulářů jsou vždycky <b>text</b>, i když vypadají jako čísla. A <code>"120" + "35"</code> je v JavaScriptu <code>"12035"</code> — plus u textu znamená slepení.</p><p>Text na číslo převedeš přes <code>Number("120")</code>. Když převést nejde, dostaneš <code>NaN</code> (Not a Number).</p>`,
    task:`Funkce <code>sectiCeny(a, b)</code> dostává ceny jako text z formuláře a vrací nesmysl. Oprav ji, ať vrací <b>číslo</b>: <code>sectiCeny("120", "35")</code> → <code>155</code>.`,
    starter:`function sectiCeny(a, b) {\n  return a + b;\n}\n\nconsole.log(sectiCeny("120", "35"));`,
    solution:`function sectiCeny(a, b) {\n  return Number(a) + Number(b);\n}\n\nconsole.log(sectiCeny("120", "35"));`,
    hints:["Podívej se do konzole: vypíše se <code>12035</code>. Texty se slepily.","Obě hodnoty převeď: <code>Number(a) + Number(b)</code>."],
    tests:[{label:"sectiCeny(\"120\", \"35\") → 155",expr:"sectiCeny(\"120\", \"35\")",expect:155},{label:"sectiCeny(\"9.5\", \"0.5\") → 10",expr:"sectiCeny(\"9.5\", \"0.5\")",expect:10}] },
  { id:"j-0d", module:"zak", xp:130, title:"Jakého typu je hodnota",
    theory:`<p><code>typeof</code> řekne, co je hodnota zač: <code>typeof 5</code> je <code>"number"</code>, <code>typeof "ahoj"</code> je <code>"string"</code>, <code>typeof true</code> je <code>"boolean"</code>.</p><p>Porovnávej vždy třemi rovnítky <code>===</code>: kontrolují hodnotu i typ. Dvě rovnítka <code>==</code> dělají tiché převody (<code>"5" == 5</code> je <code>true</code>) a vedou k chybám.</p>`,
    task:`Napiš funkci <code>popis(x)</code>: pro číslo vrátí <code>"číslo"</code>, pro text <code>"text"</code>, pro cokoliv jiného <code>"jiné"</code>.`,
    starter:`function popis(x) {\n  \n}`,
    solution:`function popis(x) {\n  if (typeof x === "number") return "číslo";\n  if (typeof x === "string") return "text";\n  return "jiné";\n}`,
    hints:["<code>if (typeof x === \"number\") return \"číslo\";</code>","Stejně pro <code>\"string\"</code>, na konci <code>return \"jiné\";</code>"],
    tests:[{label:"popis(42) → \"číslo\"",expr:"popis(42)",expect:"číslo"},{label:"popis(\"42\") → \"text\"",expr:"popis(\"42\")",expect:"text"},{label:"popis(true) → \"jiné\"",expr:"popis(true)",expect:"jiné"},{label:"popis(null) → \"jiné\"",expr:"popis(null)",expect:"jiné"}] },

  /* ======================= FUNKCE A LOGIKA ======================= */
  { id:"j-1", module:"fn", xp:120, title:"První funkce",
    theory:`<p>Funkce je pojmenovaný kus kódu, který bere vstupy a vrací výsledek:</p><p><code>function dvojnasobek(x) { return x * 2; }</code></p><p>Hodnoty si můžeš vypsat přes <code>console.log()</code> — uvidíš je v konzoli.</p>`,
    task:`Napiš funkci <code>soucet(a, b)</code>, která vrátí součet obou čísel.`,
    starter:`function soucet(a, b) {\n  \n}\n\nconsole.log(soucet(2, 3));`,
    solution:`function soucet(a, b) {\n  return a + b;\n}\n\nconsole.log(soucet(2, 3));`,
    hints:["Výsledek z funkce dostaneš přes <code>return</code>.","<code>return a + b;</code>"],
    tests:[{label:"soucet(2, 3) → 5",expr:"soucet(2, 3)",expect:5},{label:"soucet(-4, 10) → 6",expr:"soucet(-4, 10)",expect:6},{label:"soucet(0, 0) → 0",expr:"soucet(0, 0)",expect:0}] },
  { id:"j-2", module:"fn", xp:140, title:"Podmínka",
    theory:`<p><code>if</code> rozhoduje podle podmínky. Porovnání <code>&gt;=</code> vrací <code>true</code> nebo <code>false</code>.</p><p><code>if (teplota &gt; 25) { return "horko"; } else { return "ok"; }</code></p>`,
    task:`Napiš funkci <code>vstupne(vek)</code>: do 15 let (včetně) vrátí <code>"dětské"</code>, od 65 let <code>"senior"</code>, jinak <code>"plné"</code>.`,
    starter:`function vstupne(vek) {\n  \n}`,
    solution:`function vstupne(vek) {\n  if (vek <= 15) return "dětské";\n  if (vek >= 65) return "senior";\n  return "plné";\n}`,
    hints:["Dvě podmínky za sebou, na konci výchozí <code>return</code>.","<code>if (vek &lt;= 15) return \"dětské\";</code>"],
    tests:[{label:"vstupne(8) → \"dětské\"",expr:"vstupne(8)",expect:"dětské"},{label:"vstupne(15) → \"dětské\"",expr:"vstupne(15)",expect:"dětské"},{label:"vstupne(30) → \"plné\"",expr:"vstupne(30)",expect:"plné"},{label:"vstupne(65) → \"senior\"",expr:"vstupne(65)",expect:"senior"}] },
  { id:"j-4", module:"fn", xp:140, title:"Šipková funkce",
    theory:`<p>Kratší zápis funkce je <b>šipka</b>. Když tělo je jen jeden výraz, <code>return</code> i závorky můžeš vynechat:</p><pre class="mini">const dvojnasobek = x => x * 2;\nconst soucet = (a, b) => a + b;</pre><p>Zaokrouhlení na celé číslo: <code>Math.round(119.79)</code> → <code>120</code>.</p>`,
    task:`Napiš šipkovou funkci <code>sDph</code>, která k ceně připočte 21 % DPH a výsledek zaokrouhlí na celé koruny.`,
    starter:`const sDph = cena => cena;`,
    solution:`const sDph = cena => Math.round(cena * 1.21);`,
    hints:["Cena s DPH je <code>cena * 1.21</code>.","<code>const sDph = cena =&gt; Math.round(cena * 1.21);</code>"],
    tests:[{label:"sDph(100) → 121",expr:"sDph(100)",expect:121},{label:"sDph(99) → 120",expr:"sDph(99)",expect:120},{label:"sDph(0) → 0",expr:"sDph(0)",expect:0}] },
  { id:"j-5", module:"fn", xp:150, title:"Výchozí hodnota",
    theory:`<p>Parametr může mít <b>výchozí hodnotu</b> pro případ, že ho nikdo nepředá: <code>function pozdrav(jmeno = "návštěvníku")</code>.</p><p>Pozor, <code>0</code> je platná hodnota — výchozí hodnota se použije jen tehdy, když parametr chybí (je <code>undefined</code>).</p>`,
    task:`Funkce <code>cenaSDopravou(cena, doprava)</code> má mít dopravu ve výchozím stavu <code>79</code> Kč. Když někdo předá <code>0</code>, je doprava zdarma.`,
    starter:`function cenaSDopravou(cena, doprava) {\n  return cena + doprava;\n}`,
    solution:`function cenaSDopravou(cena, doprava = 79) {\n  return cena + doprava;\n}`,
    hints:["Výchozí hodnota se píše rovnou do závorky s parametry.","<code>function cenaSDopravou(cena, doprava = 79)</code>"],
    tests:[{label:"cenaSDopravou(500) → 579",expr:"cenaSDopravou(500)",expect:579},{label:"cenaSDopravou(500, 0) → 500",expr:"cenaSDopravou(500, 0)",expect:500},{label:"cenaSDopravou(500, 129) → 629",expr:"cenaSDopravou(500, 129)",expect:629}] },
  { id:"j-6", module:"fn", xp:150, title:"A zároveň, nebo",
    theory:`<p>Podmínky spojuješ: <code>&amp;&amp;</code> = a zároveň (obě musí platit), <code>||</code> = nebo (stačí jedna), <code>!</code> = negace.</p><pre class="mini">vek &gt;= 18 &amp;&amp; maVstupenku\njeVikend || jeSvatek</pre><p>Výsledek porovnání je rovnou <code>true</code>/<code>false</code> — nepotřebuješ <code>if</code>, můžeš ho vrátit.</p>`,
    task:`Napiš <code>muzeDovnitr(vek, sDoprovodem)</code>: dovnitř může každý od 18 let, mladší jen s doprovodem. Vrať <code>true</code>/<code>false</code>.`,
    starter:`function muzeDovnitr(vek, sDoprovodem) {\n  \n}`,
    solution:`function muzeDovnitr(vek, sDoprovodem) {\n  return vek >= 18 || sDoprovodem;\n}`,
    hints:["Stačí jedna z podmínek → <code>||</code>.","<code>return vek &gt;= 18 || sDoprovodem;</code>"],
    tests:[{label:"muzeDovnitr(20, false) → true",expr:"muzeDovnitr(20, false)",expect:true},{label:"muzeDovnitr(12, true) → true",expr:"muzeDovnitr(12, true)",expect:true},{label:"muzeDovnitr(12, false) → false",expr:"muzeDovnitr(12, false)",expect:false},{label:"muzeDovnitr(18, false) → true",expr:"muzeDovnitr(18, false)",expect:true}] },

  /* ======================= POLE A CYKLY ======================= */
  { id:"j-3", module:"loop", xp:160, title:"Největší číslo",
    theory:`<p>Pole je seznam hodnot: <code>[3, 9, 1]</code>. Projdeš ho cyklem <code>for (const x of pole) { … }</code>.</p><p>Existuje i zkratka <code>Math.max(...pole)</code> — uznáme obojí.</p>`,
    task:`Napiš funkci <code>nejvetsi(pole)</code>, která vrátí největší číslo v poli.`,
    starter:`function nejvetsi(pole) {\n  \n}`,
    solution:`function nejvetsi(pole) {\n  let max = pole[0];\n  for (const x of pole) {\n    if (x > max) max = x;\n  }\n  return max;\n}`,
    hints:["Začni s <code>let max = pole[0];</code> a projdi pole cyklem.","Uvnitř cyklu: <code>if (x &gt; max) max = x;</code>"],
    tests:[{label:"nejvetsi([3, 9, 1]) → 9",expr:"nejvetsi([3, 9, 1])",expect:9},{label:"nejvetsi([-5, -2, -9]) → -2",expr:"nejvetsi([-5, -2, -9])",expect:-2},{label:"nejvetsi([7]) → 7",expr:"nejvetsi([7])",expect:7}] },
  { id:"j-7", module:"loop", xp:150, title:"Součet košíku",
    theory:`<p>Typický vzor: připrav si „sběrnou“ proměnnou a v cyklu do ní přičítej.</p><pre class="mini">let celkem = 0;\nfor (const cena of ceny) {\n  celkem += cena;   // totéž co celkem = celkem + cena\n}</pre><p>Prázdné pole má součet <code>0</code> — tvoje funkce to musí zvládnout.</p>`,
    task:`Napiš <code>soucetKosiku(ceny)</code>, která sečte všechny ceny v poli.`,
    starter:`function soucetKosiku(ceny) {\n  \n}`,
    solution:`function soucetKosiku(ceny) {\n  let celkem = 0;\n  for (const cena of ceny) {\n    celkem += cena;\n  }\n  return celkem;\n}`,
    hints:["Začni <code>let celkem = 0;</code>, na konci <code>return celkem;</code>.","V cyklu <code>celkem += cena;</code>"],
    tests:[{label:"soucetKosiku([55, 75, 70]) → 200",expr:"soucetKosiku([55, 75, 70])",expect:200},{label:"soucetKosiku([]) → 0",expr:"soucetKosiku([])",expect:0}] },
  { id:"j-8", module:"loop", xp:160, title:"Bez duplicit",
    theory:`<p><code>pole.includes(x)</code> řekne, jestli je hodnota v poli. <code>pole.push(x)</code> přidá na konec.</p><p>Dobrý zvyk: neměň pole, které ti někdo předal. Udělej kopii <code>[...seznam]</code> a vrať ji — volající pak nedostane nečekanou změnu.</p>`,
    task:`Napiš <code>pridej(seznam, polozka)</code>: vrátí <b>nové</b> pole s položkou na konci. Když tam položka už je, vrátí kopii beze změny. Původní pole neměň.`,
    starter:`function pridej(seznam, polozka) {\n  seznam.push(polozka);\n  return seznam;\n}`,
    solution:`function pridej(seznam, polozka) {\n  const kopie = [...seznam];\n  if (!kopie.includes(polozka)) kopie.push(polozka);\n  return kopie;\n}`,
    hints:["Kopie pole: <code>const kopie = [...seznam];</code>","<code>if (!kopie.includes(polozka)) kopie.push(polozka);</code>"],
    tests:[{label:"pridej([\"mléko\"], \"chléb\") → [\"mléko\", \"chléb\"]",expr:"pridej([\"mléko\"], \"chléb\")",expect:["mléko","chléb"]},{label:"pridej([\"mléko\"], \"mléko\") → [\"mléko\"]",expr:"pridej([\"mléko\"], \"mléko\")",expect:["mléko"]},{label:"Původní pole zůstane beze změny",expr:"(()=>{const a=[\"káva\"];pridej(a,\"čaj\");return a})()",expect:["káva"]}] },
  { id:"j-9", module:"loop", xp:170, kind:"debug", title:"Odpočet o jedna vedle",
    theory:`<p>Klasický cyklus má tři části: <code>for (let i = 10; i &gt; 0; i--)</code> — začátek, podmínka, krok. Nejčastější chyba v programování je „o jedna vedle“ (off-by-one): <code>&gt;</code> vs <code>&gt;=</code>.</p>`,
    task:`<code>odpocet(3)</code> má vrátit <code>[3, 2, 1]</code>, ale vrací o číslo navíc. Najdi a oprav chybu.`,
    starter:`function odpocet(n) {\n  const cisla = [];\n  for (let i = n; i >= 0; i--) {\n    cisla.push(i);\n  }\n  return cisla;\n}\n\nconsole.log(odpocet(3));`,
    solution:`function odpocet(n) {\n  const cisla = [];\n  for (let i = n; i > 0; i--) {\n    cisla.push(i);\n  }\n  return cisla;\n}\n\nconsole.log(odpocet(3));`,
    hints:["Podívej se do konzole — co je navíc na konci?","Podmínka <code>i &gt;= 0</code> pustí i nulu. Má být <code>i &gt; 0</code>."],
    tests:[{label:"odpocet(3) → [3, 2, 1]",expr:"odpocet(3)",expect:[3,2,1]},{label:"odpocet(1) → [1]",expr:"odpocet(1)",expect:[1]},{label:"odpocet(0) → []",expr:"odpocet(0)",expect:[]}] },

  /* ======================= METODY POLÍ ======================= */
  { id:"ja-1", module:"arr", xp:180, title:"map: přepočítej všechno",
    slides:[{ title:"Metody polí místo cyklů", html:`<p>Většinu cyklů v praxi nahrazují metody polí. Říkají, <b>co</b> chceš, ne jak:</p><ul><li><code>map</code> — z každé položky udělej novou (stejný počet)</li><li><code>filter</code> — nech jen některé</li><li><code>find</code> — najdi první</li><li><code>reduce</code> — slož do jedné hodnoty</li></ul><pre class="mini">[1, 2, 3].map(x =&gt; x * 10)   // [10, 20, 30]</pre><p>Původní pole zůstává beze změny.</p>` }],
    task:`Napiš <code>cenySDph(ceny)</code>, která vrátí nové pole s cenami včetně 21 % DPH, zaokrouhlenými na koruny. Použij <code>map</code>.`,
    starter:`function cenySDph(ceny) {\n  \n}`,
    solution:`function cenySDph(ceny) {\n  return ceny.map(c => Math.round(c * 1.21));\n}`,
    hints:["<code>return ceny.map(c =&gt; …);</code>","<code>c =&gt; Math.round(c * 1.21)</code>"],
    tests:[{label:"cenySDph([100, 50]) → [121, 61]",expr:"cenySDph([100, 50])",expect:[121,61]},{label:"cenySDph([]) → []",expr:"cenySDph([])",expect:[]}] },
  { id:"ja-2", module:"arr", xp:180, title:"filter: jen co je skladem",
    theory:`<p><code>filter</code> nechá položky, pro které funkce vrátí <code>true</code>:</p><pre class="mini">produkty.filter(p =&gt; p.cena &lt; 100)</pre><p>Metody jde <b>řetězit</b>: <code>.filter(…).map(…)</code> — nejdřív vyber, pak přetvoř.</p>`,
    task:`Napiš <code>skladem(produkty)</code>, která vrátí <b>názvy</b> produktů, kterých je víc než 0 kusů (<code>ks &gt; 0</code>).`,
    starter:`function skladem(produkty) {\n  \n}\n\nconsole.log(skladem([\n  { nazev: "Espresso", ks: 12 },\n  { nazev: "Matcha", ks: 0 },\n  { nazev: "Filtr", ks: 3 },\n]));`,
    solution:`function skladem(produkty) {\n  return produkty.filter(p => p.ks > 0).map(p => p.nazev);\n}\n\nconsole.log(skladem([\n  { nazev: "Espresso", ks: 12 },\n  { nazev: "Matcha", ks: 0 },\n  { nazev: "Filtr", ks: 3 },\n]));`,
    hints:["Nejdřív <code>.filter(p =&gt; p.ks &gt; 0)</code>.","Pak <code>.map(p =&gt; p.nazev)</code>."],
    tests:[{label:"Vrátí [\"Espresso\", \"Filtr\"]",expr:"skladem([{nazev:\"Espresso\",ks:12},{nazev:\"Matcha\",ks:0},{nazev:\"Filtr\",ks:3}])",expect:["Espresso","Filtr"]},{label:"Nic skladem → []",expr:"skladem([{nazev:\"Matcha\",ks:0}])",expect:[]}] },
  { id:"ja-3", module:"arr", xp:180, title:"find: najdi podle id",
    theory:`<p><code>find</code> vrátí <b>první</b> položku, která vyhovuje, nebo <code>undefined</code>, když žádná není. Na rozdíl od <code>filter</code> nevrací pole.</p><pre class="mini">uzivatele.find(u =&gt; u.id === 7)</pre>`,
    task:`Napiš <code>najdi(produkty, id)</code>, která vrátí produkt s daným <code>id</code> (celý objekt), nebo <code>undefined</code>.`,
    starter:`function najdi(produkty, id) {\n  return produkty.filter(p => p.id === id);\n}`,
    solution:`function najdi(produkty, id) {\n  return produkty.find(p => p.id === id);\n}`,
    hints:["<code>filter</code> vrací pole. Chceš jeden objekt.","<code>return produkty.find(p =&gt; p.id === id);</code>"],
    tests:[{label:"Najde id 2",expr:"najdi([{id:1,nazev:\"Espresso\"},{id:2,nazev:\"Filtr\"}], 2)",expect:{id:2,nazev:"Filtr"}},{label:"Neexistující id → undefined",expr:"najdi([{id:1,nazev:\"Espresso\"}], 9) === undefined",expect:true}] },
  { id:"ja-4", module:"arr", xp:200, title:"reduce: celková cena",
    theory:`<p><code>reduce</code> projde pole a postupně skládá jednu hodnotu. Dostává <b>průběžný výsledek</b> a aktuální položku; druhý argument je počáteční hodnota:</p><pre class="mini">[1, 2, 3].reduce((soucet, x) =&gt; soucet + x, 0)   // 6</pre><p>Počáteční hodnotu nevynechávej — u prázdného pole by reduce spadl.</p>`,
    task:`Napiš <code>celkem(kosik)</code>: košík je pole <code>{ cena, ks }</code>, vrať součet <code>cena × ks</code> přes všechny položky. Použij <code>reduce</code>.`,
    starter:`function celkem(kosik) {\n  \n}`,
    solution:`function celkem(kosik) {\n  return kosik.reduce((suma, p) => suma + p.cena * p.ks, 0);\n}`,
    hints:["<code>kosik.reduce((suma, p) =&gt; …, 0)</code>","Tělo: <code>suma + p.cena * p.ks</code>"],
    tests:[{label:"2× 55 + 1× 75 → 185",expr:"celkem([{cena:55,ks:2},{cena:75,ks:1}])",expect:185},{label:"Prázdný košík → 0",expr:"celkem([])",expect:0}] },
  { id:"ja-5", module:"arr", xp:220, kind:"debug", title:"Řazení, které nic nerozbije",
    theory:`<p><code>sort</code> má dvě pasti:</p><ul><li>bez funkce řadí <b>jako text</b>: <code>[10, 9, 100].sort()</code> → <code>[10, 100, 9]</code>. Čísla řaď přes <code>(a, b) =&gt; a - b</code>.</li><li><b>mění původní pole</b>. Nová metoda <code>toSorted</code> (nebo <code>[...pole].sort(…)</code>) vrátí seřazenou kopii.</li></ul>`,
    task:`<code>podleCeny(produkty)</code> řadí správně, ale nechtěně přeskládá i původní pole v aplikaci. Oprav ji, ať vrací seřazenou <b>kopii</b> (od nejlevnějšího).`,
    starter:`function podleCeny(produkty) {\n  return produkty.sort((a, b) => a.cena - b.cena);\n}`,
    solution:`function podleCeny(produkty) {\n  return produkty.toSorted((a, b) => a.cena - b.cena);\n}`,
    hints:["<code>sort</code> mění pole, na kterém ho zavoláš.","Použij <code>toSorted</code> nebo <code>[...produkty].sort(…)</code>."],
    tests:[{label:"Seřadí od nejlevnějšího",expr:"podleCeny([{cena:75},{cena:55},{cena:70}]).map(p=>p.cena)",expect:[55,70,75]},{label:"Původní pole zůstane v původním pořadí",expr:"(()=>{const a=[{cena:75},{cena:55}];podleCeny(a);return a.map(p=>p.cena)})()",expect:[75,55]}] },
  { id:"ja-6", module:"arr", xp:240, title:"Řetězení: tři nejdražší",
    theory:`<p>Síla metod je v řetězení. Každý krok dostane výsledek předchozího:</p><pre class="mini">data\n  .filter(…)      // vyber\n  .toSorted(…)    // seřaď\n  .slice(0, 3)    // vezmi první tři\n  .map(…)         // přetvoř</pre><p><code>slice(0, 3)</code> vrátí první tři položky (nebo méně, když jich tolik není).</p>`,
    task:`Napiš <code>topTri(produkty)</code>: z produktů <b>skladem</b> (<code>ks &gt; 0</code>) vrať názvy tří nejdražších, od nejdražšího.`,
    starter:`function topTri(produkty) {\n  \n}`,
    solution:`function topTri(produkty) {\n  return produkty\n    .filter(p => p.ks > 0)\n    .toSorted((a, b) => b.cena - a.cena)\n    .slice(0, 3)\n    .map(p => p.nazev);\n}`,
    hints:["Pořadí: filter → toSorted → slice → map.","Od nejdražšího: <code>(a, b) =&gt; b.cena - a.cena</code>."],
    tests:[{label:"Vrátí 3 nejdražší skladem",expr:"topTri([{nazev:\"A\",cena:50,ks:1},{nazev:\"B\",cena:90,ks:0},{nazev:\"C\",cena:80,ks:2},{nazev:\"D\",cena:70,ks:5},{nazev:\"E\",cena:60,ks:1}])",expect:["C","D","E"]},{label:"Méně než 3 produkty → tolik, kolik jich je",expr:"topTri([{nazev:\"A\",cena:50,ks:1}])",expect:["A"]}] },

  /* ======================= OBJEKTY A JSON ======================= */
  { id:"jo-1", module:"obj", xp:170, title:"Objekt a jeho vlastnosti",
    theory:`<p>Objekt drží související hodnoty pod jmény: <code>{ jmeno: "Ada", mesto: "Brno" }</code>. K hodnotě se dostaneš tečkou <code>osoba.jmeno</code>, nebo hranatými závorkami <code>osoba["mesto"]</code> (hodí se, když je název v proměnné).</p>`,
    task:`Napiš <code>vizitka(osoba)</code>, která vrátí text ve tvaru <code>Ada Lovelace (Londýn)</code> z vlastností <code>jmeno</code>, <code>prijmeni</code> a <code>mesto</code>.`,
    starter:`function vizitka(osoba) {\n  \n}`,
    solution:`function vizitka(osoba) {\n  return \`\${osoba.jmeno} \${osoba.prijmeni} (\${osoba.mesto})\`;\n}`,
    hints:["Šablona: <code>\`\${osoba.jmeno} …\`</code>","<code>\`\${osoba.jmeno} \${osoba.prijmeni} (\${osoba.mesto})\`</code>"],
    tests:[{label:"Ada Lovelace (Londýn)",expr:"vizitka({jmeno:\"Ada\",prijmeni:\"Lovelace\",mesto:\"Londýn\"})",expect:"Ada Lovelace (Londýn)"},{label:"Jiná osoba",expr:"vizitka({mesto:\"Brno\",jmeno:\"Jan\",prijmeni:\"Novák\"})",expect:"Jan Novák (Brno)"}] },
  { id:"jo-2", module:"obj", xp:180, title:"Destrukturování",
    theory:`<p>Vlastnosti můžeš z objektu „vybalit“ rovnou do proměnných:</p><pre class="mini">const { ulice, mesto } = adresa;\n// nebo rovnou v parametrech:\nfunction f({ ulice, mesto }) { … }</pre><p>Funguje i pro pole: <code>const [prvni, druhy] = pole;</code></p>`,
    task:`Napiš <code>adresa</code> s destrukturováním v parametru: z <code>{ ulice, psc, mesto }</code> vrať <code>Veveří 42, 602 00 Brno</code>.`,
    starter:`function adresa(a) {\n  \n}`,
    solution:`function adresa({ ulice, psc, mesto }) {\n  return \`\${ulice}, \${psc} \${mesto}\`;\n}`,
    hints:["Parametr přepiš na <code>{ ulice, psc, mesto }</code>.","<code>return \`\${ulice}, \${psc} \${mesto}\`;</code>"],
    tests:[{label:"Veveří 42, 602 00 Brno",expr:"adresa({ulice:\"Veveří 42\",psc:\"602 00\",mesto:\"Brno\"})",expect:"Veveří 42, 602 00 Brno"}] },
  { id:"jo-3", module:"obj", xp:200, kind:"debug", title:"Kopie se změnou",
    theory:`<p>Objekty se předávají <b>odkazem</b>: když ho změníš ve funkci, změní se všude. Ve frameworkách (React, Vue) je to častý zdroj chyb — změna se nepozná a stránka se nepřekreslí.</p><p>Bezpečně: vytvoř nový objekt se změnou přes <b>spread</b>:</p><pre class="mini">const novy = { ...produkt, cena: 89 };</pre>`,
    task:`<code>zmenCenu(produkt, cena)</code> mění původní objekt. Oprav ji, ať vrací <b>nový</b> objekt s novou cenou a původní nechá být.`,
    starter:`function zmenCenu(produkt, cena) {\n  produkt.cena = cena;\n  return produkt;\n}`,
    solution:`function zmenCenu(produkt, cena) {\n  return { ...produkt, cena };\n}`,
    hints:["<code>{ ...produkt }</code> zkopíruje všechny vlastnosti.","<code>return { ...produkt, cena };</code> — zkratka pro <code>cena: cena</code>."],
    tests:[{label:"Vrátí objekt s novou cenou",expr:"zmenCenu({nazev:\"Filtr\",cena:70}, 89)",expect:{nazev:"Filtr",cena:89}},{label:"Původní objekt se nezmění",expr:"(()=>{const p={nazev:\"Filtr\",cena:70};zmenCenu(p,89);return p.cena})()",expect:70}] },
  { id:"jo-4", module:"obj", xp:220, title:"Počítání do objektu",
    theory:`<p>Objekt se hodí jako slovník: klíč → počet.</p><pre class="mini">const pocty = {};\nfor (const slovo of slova) {\n  pocty[slovo] = (pocty[slovo] ?? 0) + 1;\n}</pre><p><code>??</code> vrátí pravou stranu, když je levá <code>undefined</code> nebo <code>null</code> — tady při prvním výskytu.</p>`,
    task:`Napiš <code>podleKategorie(produkty)</code>, která vrátí objekt, kolik je produktů v každé kategorii, např. <code>{ kava: 2, caj: 1 }</code>.`,
    starter:`function podleKategorie(produkty) {\n  \n}`,
    solution:`function podleKategorie(produkty) {\n  const pocty = {};\n  for (const p of produkty) {\n    pocty[p.kategorie] = (pocty[p.kategorie] ?? 0) + 1;\n  }\n  return pocty;\n}`,
    hints:["Začni <code>const pocty = {};</code> a projdi produkty.","<code>pocty[p.kategorie] = (pocty[p.kategorie] ?? 0) + 1;</code>"],
    tests:[{label:"{ kava: 2, caj: 1 }",expr:"podleKategorie([{kategorie:\"kava\"},{kategorie:\"caj\"},{kategorie:\"kava\"}])",expect:{kava:2,caj:1}},{label:"Prázdné pole → {}",expr:"podleKategorie([])",expect:{}}] },
  { id:"jo-5", module:"obj", xp:230, title:"JSON a rozbitá data",
    theory:`<p>JSON je text, ve kterém si programy posílají data. <code>JSON.parse(text)</code> z něj udělá objekt, <code>JSON.stringify(obj)</code> naopak.</p><p>Data zvenku (localStorage, server) můžou být rozbitá — <code>JSON.parse</code> pak <b>vyhodí chybu</b>. Zachytíš ji přes <code>try { … } catch (e) { … }</code>.</p>`,
    task:`Napiš <code>nactiNastaveni(text)</code>: vrať objekt z JSON textu. Když je text rozbitý, vrať výchozí <code>{ motiv: "svetly" }</code>.`,
    starter:`function nactiNastaveni(text) {\n  return JSON.parse(text);\n}`,
    solution:`function nactiNastaveni(text) {\n  try {\n    return JSON.parse(text);\n  } catch (e) {\n    return { motiv: "svetly" };\n  }\n}`,
    hints:["Obal <code>JSON.parse</code> do <code>try { … }</code>.","V <code>catch (e) { return { motiv: \"svetly\" }; }</code>"],
    tests:[{label:"Platný JSON → objekt",expr:"nactiNastaveni('{\"motiv\":\"tmavy\"}')",expect:{motiv:"tmavy"}},{label:"Rozbitý text → výchozí nastavení",expr:"nactiNastaveni(\"{motiv: tmavy\")",expect:{motiv:"svetly"}}] },

  /* ======================= PRÁCE SE STRÁNKOU (DOM) ======================= */
  { id:"jd-1", module:"dom", engine:"dom", xp:200, title:"Najdi prvek a změň text",
    slides:[
      { title:"DOM = stránka jako objekty", html:`<p>Prohlížeč převede HTML na strom objektů — <b>DOM</b>. JavaScript ho může číst i měnit, a stránka se hned překreslí.</p><pre class="mini">const nadpis = document.querySelector("#nadpis");\nnadpis.textContent = "Nový text";</pre><p><code>querySelector</code> bere stejné selektory jako CSS: <code>#id</code>, <code>.trida</code>, <code>button</code>.</p>` },
      { title:"Jak to tu funguje", html:`<p>Vpravo dole uvidíš dvě okna: <b>Tvůj výsledek</b> (běží tvůj kód, můžeš klikat) a <b>Cíl</b>. Testy klikají a kontrolují v samostatné kopii stránky, takže tvůj náhled neovlivní.</p>` } ],
    task:`Najdi nadpis <code>#nadpis</code> a změň jeho text na <b>Vítej zpět!</b>`,
    html:`<h1 id="nadpis">Načítám…</h1><p>Tvůj účet je připravený.</p>`, fixed:DOM_CSS,
    starter:`const nadpis = document.querySelector("#nadpis");\n`,
    solution:`const nadpis = document.querySelector("#nadpis");\nnadpis.textContent = "Vítej zpět!";`,
    hints:["Prvek už máš v proměnné <code>nadpis</code>.","<code>nadpis.textContent = \"Vítej zpět!\";</code>"],
    tests:[{label:"Nadpis zní Vítej zpět!",expr:"document.querySelector(\"#nadpis\").textContent",expect:"Vítej zpět!"}] },
  { id:"jd-2", module:"dom", engine:"dom", xp:200, title:"Třídy místo stylů",
    theory:`<p>Vzhled nech v CSS a z JavaScriptu jen přepínej <b>třídy</b>: <code>prvek.classList.add("ok")</code>, <code>.remove(…)</code>, <code>.toggle(…)</code>, <code>.contains(…)</code>.</p><p>Psát styly přímo (<code>prvek.style.color = …</code>) jde, ale design se pak rozutíká po kódu.</p>`,
    task:`Hláška <code>.zprava</code> má po uložení dostat třídu <code>ok</code> (CSS ji obarví zeleně) a ztratit třídu <code>ceka</code>.`,
    html:`<p class="zprava ceka">Ukládám změny…</p>`, fixed:DOM_CSS+`.zprava{padding:10px 14px;border-radius:8px}.ceka{background:#e2e8f0}.ok{background:#bbf7d0;color:#14532d}`,
    starter:`const zprava = document.querySelector(".zprava");\nzprava.textContent = "Uloženo ✓";\n`,
    solution:`const zprava = document.querySelector(".zprava");\nzprava.textContent = "Uloženo ✓";\nzprava.classList.remove("ceka");\nzprava.classList.add("ok");`,
    hints:["<code>zprava.classList.add(\"ok\");</code>","A ještě <code>zprava.classList.remove(\"ceka\");</code>"],
    tests:[{label:"Má třídu ok",expr:"document.querySelector(\".zprava\").classList.contains(\"ok\")",expect:true},{label:"Nemá třídu ceka",expr:"document.querySelector(\".zprava\").classList.contains(\"ceka\")",expect:false}] },
  { id:"jd-3", module:"dom", engine:"dom", xp:220, title:"Reaguj na kliknutí",
    theory:`<p>Na událost (kliknutí, psaní, odeslání) se přihlásíš přes <code>addEventListener</code>:</p><pre class="mini">tlacitko.addEventListener("click", () =&gt; {\n  // proběhne při každém kliknutí\n});</pre><p>Stav (kolik je kusů) drž v proměnné a text jen překresli podle ní.</p>`,
    task:`Tlačítko <b>+</b> má zvýšit počet v <code>#pocet</code> o 1 při každém kliknutí.`,
    html:`<p>Espresso: <b id="pocet">0</b> ks <button id="plus" aria-label="Přidat kus">+</button></p>`, fixed:DOM_CSS,
    starter:`const plus = document.querySelector("#plus");\nconst pocetEl = document.querySelector("#pocet");\nlet pocet = 0;\n\n`,
    solution:`const plus = document.querySelector("#plus");\nconst pocetEl = document.querySelector("#pocet");\nlet pocet = 0;\n\nplus.addEventListener("click", () => {\n  pocet++;\n  pocetEl.textContent = pocet;\n});`,
    hints:["<code>plus.addEventListener(\"click\", () =&gt; { … });</code>","Uvnitř: <code>pocet++;</code> a <code>pocetEl.textContent = pocet;</code>"],
    tests:[{label:"Po jednom kliknutí je 1",act:"document.querySelector(\"#plus\").click()",expr:"document.querySelector(\"#pocet\").textContent",expect:"1"},{label:"Po dalších dvou je 3",act:"document.querySelector(\"#plus\").click();document.querySelector(\"#plus\").click()",expr:"document.querySelector(\"#pocet\").textContent",expect:"3"}] },
  { id:"jd-4", module:"dom", engine:"dom", xp:240, title:"Vytváření prvků (a bezpečně)",
    theory:`<p>Nový prvek: <code>document.createElement("li")</code>, text do něj přes <code>textContent</code> a vložit přes <code>seznam.append(li)</code>.</p><p><b>Bezpečnost:</b> <code>innerHTML</code> text vykládá jako HTML. Kdyby úkol napsal útočník, může do stránky propašovat vlastní kód (XSS). <code>textContent</code> vloží vždy jen text.</p>`,
    task:`Vypiš všechny úkoly z pole <code>ukoly</code> jako <code>li</code> do <code>#seznam</code>. Pozor, jeden úkol obsahuje HTML značky — mají se zobrazit jako text.`,
    html:`<h3>Úkoly na dnes</h3><ul id="seznam"></ul>`, fixed:DOM_CSS,
    starter:`const ukoly = ["Koupit kávu", "Zalít kytky", "Opravit <b>tučné</b> písmo"];\nconst seznam = document.querySelector("#seznam");\n\nseznam.innerHTML = ukoly.join("<br>");`,
    solution:`const ukoly = ["Koupit kávu", "Zalít kytky", "Opravit <b>tučné</b> písmo"];\nconst seznam = document.querySelector("#seznam");\n\nfor (const ukol of ukoly) {\n  const li = document.createElement("li");\n  li.textContent = ukol;\n  seznam.append(li);\n}`,
    hints:["Pro každý úkol: <code>const li = document.createElement(\"li\");</code>","<code>li.textContent = ukol; seznam.append(li);</code>"],
    tests:[{label:"Seznam má 3 položky li",expr:"document.querySelectorAll(\"#seznam > li\").length",expect:3},{label:"Texty sedí",expr:"[...document.querySelectorAll(\"#seznam > li\")].map(l=>l.textContent)",expect:["Koupit kávu","Zalít kytky","Opravit <b>tučné</b> písmo"]},{label:"Žádné HTML se nevložilo",expr:"document.querySelectorAll(\"#seznam b\").length",expect:0}] },
  { id:"jd-5", module:"dom", engine:"dom", xp:240, title:"Formulář bez obnovení stránky",
    theory:`<p>Odeslání formuláře stránku normálně znovu načte. Když ho chceš zpracovat v JavaScriptu, poslouchej <code>submit</code> na formuláři a zavolej <code>e.preventDefault()</code>.</p><p>Hodnotu pole přečteš z <code>input.value</code>. Poslouchej <code>submit</code>, ne <code>click</code> na tlačítku — formulář jde odeslat i Enterem.</p>`,
    task:`Po odeslání formuláře <code>#f</code> vypiš do <code>#vystup</code> text <b>Ahoj, Ada!</b> (podle zadaného jména) a pole vyprázdni.`,
    html:`<form id="f"><label for="jmeno">Jméno</label> <input id="jmeno"> <button>Pozdravit</button></form><p id="vystup"></p>`, fixed:DOM_CSS,
    starter:`const form = document.querySelector("#f");\nconst input = document.querySelector("#jmeno");\nconst vystup = document.querySelector("#vystup");\n\n`,
    solution:`const form = document.querySelector("#f");\nconst input = document.querySelector("#jmeno");\nconst vystup = document.querySelector("#vystup");\n\nform.addEventListener("submit", e => {\n  e.preventDefault();\n  vystup.textContent = \`Ahoj, \${input.value}!\`;\n  input.value = "";\n});`,
    hints:["<code>form.addEventListener(\"submit\", e =&gt; { e.preventDefault(); … });</code>","<code>vystup.textContent = \`Ahoj, \${input.value}!\`; input.value = \"\";</code>"],
    tests:[{label:"Po odeslání se vypíše Ahoj, Ada!",act:"document.querySelector(\"#jmeno\").value=\"Ada\";document.querySelector(\"#f\").requestSubmit()",expr:"document.querySelector(\"#vystup\").textContent",expect:"Ahoj, Ada!"},{label:"Pole se vyprázdní",expr:"document.querySelector(\"#jmeno\").value",expect:""}] },
  { id:"jd-6", module:"dom", engine:"dom", xp:260, title:"Jeden posluchač pro všechny",
    theory:`<p>Když přidáš posluchač ke každému tlačítku zvlášť, tlačítka přidaná <b>později</b> fungovat nebudou. <b>Delegace událostí</b>: jeden posluchač na rodiči a v něm zjisti, na co se kliklo:</p><pre class="mini">seznam.addEventListener("click", e =&gt; {\n  const btn = e.target.closest(".smazat");\n  if (!btn) return;\n  btn.closest("li").remove();\n});</pre>`,
    task:`Tlačítka <b>×</b> mažou položky, ale jen ty, co byly na stránce od začátku. Přepiš kód na delegaci, ať fungují i položky přidané později.`,
    html:`<ul id="seznam"><li>Espresso <button class="smazat" aria-label="Odebrat">×</button></li><li>Filtr <button class="smazat" aria-label="Odebrat">×</button></li><li>Matcha <button class="smazat" aria-label="Odebrat">×</button></li></ul>`, fixed:DOM_CSS+`li{margin:4px 0}.smazat{padding:2px 8px;margin-left:6px;background:#e11d48}`,
    starter:`const seznam = document.querySelector("#seznam");\n\ndocument.querySelectorAll(".smazat").forEach(btn => {\n  btn.addEventListener("click", () => btn.closest("li").remove());\n});`,
    solution:`const seznam = document.querySelector("#seznam");\n\nseznam.addEventListener("click", e => {\n  const btn = e.target.closest(".smazat");\n  if (!btn) return;\n  btn.closest("li").remove();\n});`,
    hints:["Posluchač dej na <code>seznam</code>, ne na tlačítka.","<code>const btn = e.target.closest(\".smazat\"); if (!btn) return;</code>"],
    tests:[{label:"Smazání první položky",act:"document.querySelector(\".smazat\").click()",expr:"document.querySelectorAll(\"#seznam li\").length",expect:2},{label:"Funguje i nově přidaná položka",act:"const li=document.createElement(\"li\");li.innerHTML='Nová <button class=\"smazat\">×</button>';document.querySelector(\"#seznam\").append(li);li.querySelector(\"button\").click()",expr:"document.querySelectorAll(\"#seznam li\").length",expect:2}] },

  /* ======================= ASYNCHRONNÍ JS ======================= */
  { id:"jas-1", module:"async", xp:260, title:"Promise: slib výsledku",
    slides:[{ title:"Proč async", html:`<p>Některé věci trvají: načtení dat ze serveru, časovač. JavaScript na ně nečeká se zamrzlou stránkou — dostaneš <b>Promise</b>, slib, že výsledek přijde později.</p><pre class="mini">new Promise(hotovo =&gt; setTimeout(hotovo, 500))</pre><p>Promise zavolá <code>hotovo</code> (resolve), až je výsledek, nebo <code>chyba</code> (reject), když se to nepovede.</p>` }],
    task:`Napiš <code>pockej(ms)</code>, která vrátí Promise, jež se splní po <code>ms</code> milisekundách.`,
    starter:`function pockej(ms) {\n  \n}`,
    solution:`function pockej(ms) {\n  return new Promise(hotovo => setTimeout(hotovo, ms));\n}`,
    hints:["<code>return new Promise(hotovo =&gt; …);</code>","Uvnitř <code>setTimeout(hotovo, ms)</code>."],
    tests:[{label:"Vrací Promise",expr:"pockej(1) instanceof Promise",expect:true},{label:"Opravdu počká aspoň 50 ms",expr:"(async()=>{const t=Date.now();await pockej(50);return Date.now()-t>=45})()",expect:true}] },
  { id:"jas-2", module:"async", xp:260, title:"async a await",
    theory:`<p><code>await</code> počká na Promise a dá ti jeho výsledek — kód se čte jako normální, shora dolů. Smí být jen uvnitř funkce označené <code>async</code>, a ta pak sama vrací Promise.</p><pre class="mini">async function jmeno(id) {\n  const u = await nactiUzivatele(id);\n  return u.jmeno;\n}</pre>`,
    task:`Napiš <code>async</code> funkci <code>jmenoUzivatele(id)</code>, která přes připravenou <code>nactiUzivatele(id)</code> načte uživatele a vrátí jeho jméno.`,
    prelude:FAKE_USERS,
    starter:`function jmenoUzivatele(id) {\n  const u = nactiUzivatele(id);\n  return u.jmeno;\n}`,
    solution:`async function jmenoUzivatele(id) {\n  const u = await nactiUzivatele(id);\n  return u.jmeno;\n}`,
    hints:["Bez <code>await</code> je <code>u</code> jen Promise, ne uživatel.","Přidej <code>async</code> před <code>function</code> a <code>await</code> před <code>nactiUzivatele</code>."],
    tests:[{label:"jmenoUzivatele(1) → \"Ada\"",expr:"jmenoUzivatele(1)",expect:"Ada"},{label:"jmenoUzivatele(2) → \"Linus\"",expr:"jmenoUzivatele(2)",expect:"Linus"}] },
  { id:"jas-3", module:"async", xp:280, title:"Když server odmítne",
    theory:`<p>Odmítnutá Promise (reject) se v <code>async</code> funkci chová jako vyhozená chyba. Zachytíš ji normálně přes <code>try/catch</code>:</p><pre class="mini">try {\n  const u = await nactiUzivatele(id);\n} catch (e) {\n  // e.message: co se pokazilo\n}</pre><p>Bez toho chyba „probublá“ výš a aplikace může spadnout.</p>`,
    task:`Napiš <code>bezpecneJmeno(id)</code>: vrať jméno uživatele, nebo <code>"Neznámý"</code>, když uživatel neexistuje.`,
    prelude:FAKE_USERS,
    starter:`async function bezpecneJmeno(id) {\n  const u = await nactiUzivatele(id);\n  return u.jmeno;\n}`,
    solution:`async function bezpecneJmeno(id) {\n  try {\n    const u = await nactiUzivatele(id);\n    return u.jmeno;\n  } catch (e) {\n    return "Neznámý";\n  }\n}`,
    hints:["Obal načtení do <code>try { … }</code>.","<code>catch (e) { return \"Neznámý\"; }</code>"],
    tests:[{label:"bezpecneJmeno(1) → \"Ada\"",expr:"bezpecneJmeno(1)",expect:"Ada"},{label:"bezpecneJmeno(99) → \"Neznámý\"",expr:"bezpecneJmeno(99)",expect:"Neznámý"}] },
  { id:"jas-4", module:"async", xp:300, title:"Paralelně je rychleji",
    theory:`<p><code>await</code> v cyklu čeká na jedno po druhém: tři dotazy po 100 ms = 300 ms. Když na sobě nezávisí, spusť je <b>najednou</b> a počkej na všechny:</p><pre class="mini">const vysledky = await Promise.all(ids.map(id =&gt; nacti(id)));</pre><p>Teď to trvá jen tak dlouho jako nejpomalejší z nich.</p>`,
    task:`<code>celkovaCena(ids)</code> načítá produkty jeden po druhém a je pomalá. Přepiš ji přes <code>Promise.all</code>, ať jsou 3 produkty hotové pod 250 ms.`,
    prelude:`// každý dotaz trvá 100 ms\nconst CENIK = { 1: 55, 2: 75, 3: 70 };\nconst nactiProdukt = id => new Promise(ok => setTimeout(() => ok({ id, cena: CENIK[id] }), 100));`,
    starter:`async function celkovaCena(ids) {\n  let suma = 0;\n  for (const id of ids) {\n    const p = await nactiProdukt(id);\n    suma += p.cena;\n  }\n  return suma;\n}`,
    solution:`async function celkovaCena(ids) {\n  const produkty = await Promise.all(ids.map(id => nactiProdukt(id)));\n  return produkty.reduce((suma, p) => suma + p.cena, 0);\n}`,
    hints:["<code>const produkty = await Promise.all(ids.map(id =&gt; nactiProdukt(id)));</code>","Pak sečti: <code>produkty.reduce((s, p) =&gt; s + p.cena, 0)</code>"],
    tests:[{label:"Cena [1, 2, 3] je 200",expr:"celkovaCena([1,2,3])",expect:200},{label:"Hotovo pod 250 ms",expr:"(async()=>{const t=Date.now();await celkovaCena([1,2,3]);return Date.now()-t<250})()",expect:true}] },
  { id:"jas-5", module:"async", xp:320, title:"fetch: data ze serveru",
    theory:`<p><code>fetch(url)</code> stáhne odpověď ze serveru. Dvě věci, na které se zapomíná:</p><ul><li>odpověď 404 nebo 500 <b>není chyba</b> pro fetch — zkontroluj <code>odpoved.ok</code> a případně chybu vyhoď sám: <code>throw new Error("HTTP " + odpoved.status)</code></li><li>tělo je potřeba přečíst: <code>await odpoved.json()</code></li></ul><p>Tady je fetch falešný (viz připravený kód), ale chová se jako skutečný.</p>`,
    task:`Napiš <code>pocasi(mesto)</code>: načti <code>/api/pocasi?mesto=…</code> a vrať text <code>Brno: 18 °C</code>. Když odpověď není ok, vyhoď chybu se zprávou <code>HTTP 404</code> (podle statusu).`,
    prelude:`// falešný server: zná jen Brno a Prahu\nconst DATA = { Brno: 18, Praha: 16 };\nconst fetch = async url => {\n  const mesto = new URL(url, "https://kaskada.test").searchParams.get("mesto");\n  const t = DATA[mesto];\n  return { ok: t !== undefined, status: t !== undefined ? 200 : 404,\n    json: async () => ({ mesto, teplota: t }) };\n};`,
    starter:`async function pocasi(mesto) {\n  const odpoved = await fetch(\`/api/pocasi?mesto=\${mesto}\`);\n  \n}`,
    solution:`async function pocasi(mesto) {\n  const odpoved = await fetch(\`/api/pocasi?mesto=\${mesto}\`);\n  if (!odpoved.ok) throw new Error("HTTP " + odpoved.status);\n  const data = await odpoved.json();\n  return \`\${data.mesto}: \${data.teplota} °C\`;\n}`,
    hints:["Nejdřív <code>if (!odpoved.ok) throw new Error(\"HTTP \" + odpoved.status);</code>","Pak <code>const data = await odpoved.json();</code> a vrať šablonu."],
    tests:[{label:"pocasi(\"Brno\") → \"Brno: 18 °C\"",expr:"pocasi(\"Brno\")",expect:"Brno: 18 °C"},{label:"Neznámé město vyhodí chybu HTTP 404",expr:"pocasi(\"Atlantida\").then(()=>\"bez chyby\",e=>e.message)",expect:"HTTP 404"}] },

  /* ======================= MODERNÍ JS ======================= */
  { id:"jm-1", module:"modern", xp:260, title:"?. a ??",
    theory:`<p><code>?.</code> (optional chaining) se zastaví, když je hodnota <code>null</code>/<code>undefined</code>, místo aby spadl: <code>uzivatel?.adresa?.mesto</code>.</p><p><code>??</code> dá výchozí hodnotu jen pro <code>null</code>/<code>undefined</code>. Na rozdíl od <code>||</code> nechá platné „prázdné“ hodnoty jako <code>0</code> nebo <code>""</code>.</p>`,
    task:`Napiš <code>mesto(u)</code>: vrať <code>u.adresa.mesto</code>, nebo <code>"neuvedeno"</code>, když chybí uživatel, adresa nebo město. Prázdný text <code>""</code> je platná hodnota.`,
    starter:`function mesto(u) {\n  return u.adresa.mesto || "neuvedeno";\n}`,
    solution:`function mesto(u) {\n  return u?.adresa?.mesto ?? "neuvedeno";\n}`,
    hints:["<code>u?.adresa?.mesto</code> nespadne na chybějící hodnotě.","<code>||</code> nahraď <code>??</code>, ať projde prázdný text."],
    tests:[{label:"Celá adresa → Brno",expr:"mesto({adresa:{mesto:\"Brno\"}})",expect:"Brno"},{label:"Bez adresy → neuvedeno",expr:"mesto({})",expect:"neuvedeno"},{label:"null → neuvedeno",expr:"mesto(null)",expect:"neuvedeno"},{label:"Prázdné město zůstane \"\"",expr:"mesto({adresa:{mesto:\"\"}})",expect:""}] },
  { id:"jm-2", module:"modern", xp:260, title:"Set: unikátní hodnoty",
    theory:`<p><code>Set</code> je množina — každou hodnotu drží jen jednou. Z pole s duplicitami uděláš unikátní pole jedním řádkem:</p><pre class="mini">[...new Set(["a", "b", "a"])]   // ["a", "b"]</pre><p><code>flatMap</code> je map, který výsledná pole rovnou spojí do jednoho.</p>`,
    task:`Napiš <code>stitky(produkty)</code>: každý produkt má pole <code>stitky</code>. Vrať všechny štítky bez duplicit, abecedně seřazené.`,
    starter:`function stitky(produkty) {\n  \n}`,
    solution:`function stitky(produkty) {\n  return [...new Set(produkty.flatMap(p => p.stitky))].toSorted();\n}`,
    hints:["Všechny štítky do jednoho pole: <code>produkty.flatMap(p =&gt; p.stitky)</code>","<code>[...new Set(…)].toSorted()</code>"],
    tests:[{label:"Unikátní a seřazené",expr:"stitky([{stitky:[\"vegan\",\"bio\"]},{stitky:[\"bio\",\"akce\"]}])",expect:["akce","bio","vegan"]},{label:"Žádné produkty → []",expr:"stitky([])",expect:[]}] },
  { id:"jm-3", module:"modern", xp:280, title:"Uzávěry",
    theory:`<p>Funkce si pamatuje proměnné z místa, kde vznikla — i když to místo už doběhlo. Tomu se říká <b>uzávěr</b> (closure):</p><pre class="mini">function vytvorPocitadlo() {\n  let n = 0;\n  return () =&gt; ++n;\n}</pre><p>Proměnná <code>n</code> je zvenku nedostupná — je soukromá. Každé volání <code>vytvorPocitadlo()</code> má vlastní <code>n</code>.</p>`,
    task:`Napiš <code>vytvorPocitadlo()</code>, která vrátí objekt s metodami <code>pricti()</code> (zvýší o 1) a <code>hodnota()</code> (vrátí aktuální stav). Dvě počítadla se nesmí ovlivňovat.`,
    starter:`let n = 0;\n\nfunction vytvorPocitadlo() {\n  return {\n    pricti: () => n++,\n    hodnota: () => n,\n  };\n}`,
    solution:`function vytvorPocitadlo() {\n  let n = 0;\n  return {\n    pricti: () => n++,\n    hodnota: () => n,\n  };\n}`,
    hints:["Teď mají všechna počítadla jedno společné <code>n</code>.","Přesuň <code>let n = 0;</code> dovnitř funkce."],
    tests:[{label:"Počítá",expr:"(()=>{const p=vytvorPocitadlo();p.pricti();p.pricti();return p.hodnota()})()",expect:2},{label:"Dvě počítadla jsou nezávislá",expr:"(()=>{const a=vytvorPocitadlo(),b=vytvorPocitadlo();a.pricti();a.pricti();b.pricti();return [a.hodnota(),b.hodnota()]})()",expect:[2,1]}] },
  { id:"jm-4", module:"modern", xp:280, title:"Neměnné úpravy polí",
    theory:`<p>Novější metody vrací <b>kopii</b> se změnou, místo aby měnily pole: <code>toSorted</code>, <code>toReversed</code>, <code>toSpliced</code> a <code>with(index, hodnota)</code>.</p><pre class="mini">["a", "b", "c"].with(1, "B")   // ["a", "B", "c"]\n["a", "b", "c"].at(-1)         // "c" — poslední</pre>`,
    task:`Napiš <code>oznacHotovo(ukoly, i)</code>: vrať nové pole, ve kterém má úkol na pozici <code>i</code> vlastnost <code>hotovo: true</code>. Původní pole ani objekty neměň.`,
    starter:`function oznacHotovo(ukoly, i) {\n  ukoly[i].hotovo = true;\n  return ukoly;\n}`,
    solution:`function oznacHotovo(ukoly, i) {\n  return ukoly.with(i, { ...ukoly[i], hotovo: true });\n}`,
    hints:["Nový objekt úkolu: <code>{ ...ukoly[i], hotovo: true }</code>","<code>return ukoly.with(i, …);</code>"],
    tests:[{label:"Úkol je hotový",expr:"oznacHotovo([{t:\"A\",hotovo:false},{t:\"B\",hotovo:false}],1)",expect:[{t:"A",hotovo:false},{t:"B",hotovo:true}]},{label:"Původní data zůstala",expr:"(()=>{const u=[{t:\"A\",hotovo:false}];oznacHotovo(u,0);return u[0].hotovo})()",expect:false}] },
  { id:"jm-5", module:"modern", xp:300, title:"Třída",
    theory:`<p><code>class</code> spojí data a funkce, které s nimi pracují. <code>constructor</code> připraví stav, metody ho mění, <code>get</code> udělá vlastnost, která se počítá:</p><pre class="mini">class Kosik {\n  #polozky = [];          // # = soukromé\n  pridej(nazev, cena) { … }\n  get celkem() { … }\n}</pre>`,
    task:`Napiš třídu <code>Kosik</code> s metodou <code>pridej(nazev, cena)</code> a vlastnostmi <code>pocet</code> a <code>celkem</code> (getter).`,
    starter:`class Kosik {\n  \n}`,
    solution:`class Kosik {\n  #polozky = [];\n\n  pridej(nazev, cena) {\n    this.#polozky.push({ nazev, cena });\n  }\n\n  get pocet() {\n    return this.#polozky.length;\n  }\n\n  get celkem() {\n    return this.#polozky.reduce((s, p) => s + p.cena, 0);\n  }\n}`,
    hints:["Pole položek: <code>#polozky = [];</code>, v metodě <code>this.#polozky.push({ nazev, cena });</code>","<code>get pocet() { return this.#polozky.length; }</code> a podobně celkem přes reduce."],
    tests:[{label:"Prázdný košík",expr:"(()=>{const k=new Kosik();return [k.pocet,k.celkem]})()",expect:[0,0]},{label:"Dvě položky",expr:"(()=>{const k=new Kosik();k.pridej(\"Espresso\",55);k.pridej(\"Filtr\",70);return [k.pocet,k.celkem]})()",expect:[2,125]}] },

  /* ======================= PROJEKT ======================= */
  { id:"jb-1", module:"jboss", engine:"dom", xp:600, boss:true, wide:true, title:"Kavárenský košík",
    theory:`<p>Projekt z praxe: menu kavárny a košík. Drž <b>stav</b> v poli <code>kosik</code> a po každé změně celý košík <b>překresli</b> funkcí <code>vykresli()</code>. Na tomhle vzoru stojí React i Vue.</p>`,
    task:`1) Kliknutí na <b>Přidat</b> přidá produkt do košíku jako <code>li</code> s textem <code>Espresso – 55 Kč</code><br>2) <code>#celkem</code> ukazuje součet, např. <code>130 Kč</code><br>3) <b>Vyprázdnit</b> košík smaže<br>4) Použij delegaci na <code>#menu</code> — fungovat musí i produkty přidané později`,
    prelude:`// produkty podle data-id tlačítek\nconst MENU = {\n  espresso: { nazev: "Espresso", cena: 55 },\n  cappuccino: { nazev: "Cappuccino", cena: 75 },\n  filtr: { nazev: "Filtr", cena: 70 },\n};`,
    html:`<div class="kav"><section><h3>Menu</h3><ul id="menu"><li>Espresso · 55 Kč <button data-id="espresso">Přidat</button></li><li>Cappuccino · 75 Kč <button data-id="cappuccino">Přidat</button></li></ul></section><section><h3>Košík</h3><ul id="kosik"></ul><p>Celkem: <strong id="celkem">0 Kč</strong></p><button id="vyprazdnit" type="button">Vyprázdnit</button></section></div>`,
    fixed:DOM_CSS+`.kav{display:grid;grid-template-columns:1fr 1fr;gap:16px}section{border:1px solid #cbd5e1;border-radius:10px;padding:10px 14px}h3{margin:0 0 6px}#menu{list-style:none;padding:0}#menu li{display:flex;justify-content:space-between;align-items:center;margin:6px 0}#menu button{padding:4px 10px}#vyprazdnit{background:#e11d48}`,
    starter:`const kosik = [];\nconst menu = document.querySelector("#menu");\nconst seznam = document.querySelector("#kosik");\nconst celkem = document.querySelector("#celkem");\n\nfunction vykresli() {\n  // překresli seznam a celkovou cenu podle pole kosik\n}\n\n// sem posluchače\n`,
    solution:`const kosik = [];\nconst menu = document.querySelector("#menu");\nconst seznam = document.querySelector("#kosik");\nconst celkem = document.querySelector("#celkem");\n\nfunction vykresli() {\n  seznam.replaceChildren(...kosik.map(p => {\n    const li = document.createElement("li");\n    li.textContent = \`\${p.nazev} – \${p.cena} Kč\`;\n    return li;\n  }));\n  const suma = kosik.reduce((s, p) => s + p.cena, 0);\n  celkem.textContent = \`\${suma} Kč\`;\n}\n\nmenu.addEventListener("click", e => {\n  const btn = e.target.closest("button[data-id]");\n  if (!btn) return;\n  kosik.push(MENU[btn.dataset.id]);\n  vykresli();\n});\n\ndocument.querySelector("#vyprazdnit").addEventListener("click", () => {\n  kosik.length = 0;\n  vykresli();\n});`,
    hints:["Posluchač na <code>menu</code>: <code>const btn = e.target.closest(\"button[data-id]\")</code>, produkt je <code>MENU[btn.dataset.id]</code>.","V <code>vykresli()</code>: <code>seznam.replaceChildren(...kosik.map(…))</code> a součet přes <code>reduce</code>."],
    tests:[
      {group:"Přidání", label:"Přidat Espresso → položka v košíku",act:"document.querySelector('[data-id=\"espresso\"]').click()",expr:"[...document.querySelectorAll(\"#kosik li\")].map(l=>l.textContent.trim())",expect:["Espresso – 55 Kč"]},
      {group:"Přidání", label:"Další dvě položky",act:"document.querySelector('[data-id=\"cappuccino\"]').click();document.querySelector('[data-id=\"espresso\"]').click()",expr:"document.querySelectorAll(\"#kosik li\").length",expect:3},
      {group:"Cena", label:"Celkem 185 Kč",expr:"document.querySelector(\"#celkem\").textContent",expect:"185 Kč"},
      {group:"Vyprázdnění", label:"Vyprázdnit smaže položky",act:"document.querySelector(\"#vyprazdnit\").click()",expr:"document.querySelectorAll(\"#kosik li\").length",expect:0},
      {group:"Vyprázdnění", label:"Po vyprázdnění 0 Kč",expr:"document.querySelector(\"#celkem\").textContent",expect:"0 Kč"},
      {group:"Delegace", label:"Funguje i nový produkt v menu",act:"const li=document.createElement(\"li\");li.innerHTML='Filtr · 70 Kč <button data-id=\"filtr\">Přidat</button>';document.querySelector(\"#menu\").append(li);li.querySelector(\"button\").click()",expr:"[...document.querySelectorAll(\"#kosik li\")].map(l=>l.textContent.trim())",expect:["Filtr – 70 Kč"]} ] },
  ],
  achievements:[
    {id:"js-zak",   name:"Proměnlivý", desc:"Dokonči modul Proměnné a hodnoty.", glyph:"x=", color:"var(--c-js)", test:(s,cs)=>moduleDone(cs,"js","zak")},
    {id:"js-fn",    name:"Funkcionář", desc:"Dokonči modul Funkce a logika.", glyph:"f()", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"js","fn")},
    {id:"js-loop",  name:"Smyčkař", desc:"Dokonči modul Pole a cykly.", glyph:"[ ]", color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"js","loop")},
    {id:"js-arr",   name:"Mapovač", desc:"Dokonči modul Metody polí.", glyph:".map", color:"var(--m-border)", test:(s,cs)=>moduleDone(cs,"js","arr")},
    {id:"js-obj",   name:"Objektivní", desc:"Dokonči modul Objekty a JSON.", glyph:"{ }", color:"var(--m-margin)", test:(s,cs)=>moduleDone(cs,"js","obj")},
    {id:"js-dom",   name:"Loutkář DOMu", desc:"Dokonči modul Práce se stránkou.", glyph:"$", color:"var(--c-js)", test:(s,cs)=>moduleDone(cs,"js","dom")},
    {id:"js-async", name:"Trpělivý", desc:"Dokonči modul Asynchronní JS.", glyph:"⏳", color:"var(--m-content)", test:(s,cs)=>moduleDone(cs,"js","async")},
    {id:"js-modern",name:"Moderní mág", desc:"Dokonči modul Moderní JS.", glyph:"✦", color:"var(--m-padding)", test:(s,cs)=>moduleDone(cs,"js","modern")},
    {id:"js-cart",  name:"Barista kódu", desc:"Postav Kavárenský košík.", glyph:"★", color:"var(--accent)", test:(s,cs)=>!!cs.done["jb-1"]},
  ]
});
